adobecom/cc

.github/codeql/codeql-config.yml
.github/workflows/codeql.yml
.github/workflows/run-tests.yaml

Add CodeQL and code coverage bot in github workflow

---

404.html

Create 404.html page. Milo provides a 404 page template. Adding it to CC repo.
Resolves: MWPW-128624
I have kept script path as cclibs/scripts/scripts.js as file is moved to this path in PR https://github.com/adobecom/cc/pull/11
TestURLs:
N/A

create 404.html page

---

.eslintrc.js
cc/blocks/promotion/promotion.css
cc/scripts/fallback.js
package-lock.json
package.json

* Improve test code linting and fix all the existing linting issues
Resolves: [MWPW-129151](https://jira.corp.adobe.com/browse/MWPW-129151)
**Test URLs:**
N/A
Verified on local no more lint issues

Improve test code linting and fix all the existing linting issues

---

README.md

* Add details on how to run linter in readme
**Test URLs:**
N/A

Adding Linting details in Readme

---

.github/workflows/run-tests.yaml

* Add lint check to github workflow
Resolves: [MWPW-129374](https://jira.corp.adobe.com/browse/MWPW-129374)
**Test URLs:**
N/A

Add lint check to the github workflow

---

package.json

Resolves: [MWPW-127801](https://jira.corp.adobe.com/browse/MWPW-127801)
**Test URLs:**
- Before: NA
- After: NA

MWPW-127801 Changing eslint folders to creativecloud

---

.github/workflows/codeql.yml
.github/workflows/run-tests.yaml

* Adding github workflow for stage branch
Resolves: [MWPW-129671](https://jira.corp.adobe.com/browse/MWPW-129671)
**Test URLs:**
N/A

GitHub workflow

---

creativecloud/features/article-promotion.js
creativecloud/scripts/scripts.js

* Fix for previewing a promotion page
Resolves: [[MWPW-129761](https://jira.corp.adobe.com/browse/MWPW-129761)]
**Test URLs:**
- Before: https://stage--cc--adobecom.hlx.page/creativecloud/promotions/hub/ccx-design-links?martech=off
- After: https://stage--cc--ruchika4.hlx.page/creativecloud/promotions/hub/ccx-design-links?martech=off

Fix preview page for promotions

---

creativecloud/scripts/scripts.js

* Enabling lana logging in cc milo
Resolves: [MWPW-130204](https://jira.corp.adobe.com/browse/MWPW-130204)
**Test URLs:**
- Before: https://stage--cc--adobecom.hlx.live/creativecloud/design/hub/guides/add-elegance-or-vintage-flair-with-dusty-rose?martech=off
- After: https://enablelana--cc--aishwaryamathuria.hlx.live/creativecloud/design/hub/guides/add-elegance-or-vintage-flair-with-dusty-rose?martech=off

MWPW-130204 Enabling lana for cc

---

helix-sitemap.yaml

Reverts adobecom/cc#48
Issue didn't got fixed hence reverting the PR

Revert "Helix query fix"

---

helix-sitemap.yaml

Revert "Take2: Fix for duplicate data in us sitemap"

---

fstab.yaml

* Changing sharepoint for CC
Resolves: [MWPW-129839](https://jira.corp.adobe.com/browse/MWPW-129839)
Test URLs:
Before: https://main--cc--adobecom.hlx.page/?martech=off
After: https://stage--cc--adobecom.hlx.page/?martech=off

MWPW-129839 Changing sharepoint for CC

---

fstab.yaml
helix-sitemap.yaml

* Changing sharepoint for CC
Resolves: [MWPW-129839](https://jira.corp.adobe.com/browse/MWPW-129839)
**Test URLs:**
- After: https://stage--cc--adobecom.hlx.page/?martech=off

MWPW-129839 Changing sharepoint for CC (stage merge from main)

---

creativecloud/scripts/scripts.js
creativecloud/sitemap-index.xml
helix-query.yaml
helix-sitemap.yaml

* Update contentRoot to cc-shared in stage branch
Resolves: [MWPW-130778](https://jira.corp.adobe.com/browse/MWPW-130778)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/creativecloud/video/hub/guides/avoid-continuity-errors-in-film?martech=off
- After: https://contentRoot--cc--adobecom.hlx.page/creativecloud/video/hub/guides/avoid-continuity-errors-in-film?martech=off
Note: Note do not merge this PR till the content has been moved in sharepoint also.

[Stage] MWPW-130778-update contentRoot to cc-shared 

---

creativecloud/scripts/scripts.js
creativecloud/sitemap-index.xml
helix-query.yaml
helix-sitemap.yaml

* Update contentRoot to cc-shared
Resolves: [MWPW-130778](https://jira.corp.adobe.com/browse/MWPW-130778)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/creativecloud/video/hub/guides/avoid-continuity-errors-in-film?martech=off
- After: https://main--cc--ruchika4.hlx.page/creativecloud/video/hub/guides/avoid-continuity-errors-in-film?martech=off
Note: Note do not merge this PR till the content has been moved in sharepoint also.

MWPW-130778-update contentRoot to cc-shared

---

helix-query.yaml

Update exclude paths to include cc-shared
Resolves: [MWPW-130778](https://jira.corp.adobe.com/browse/MWPW-130778)
Test URLs:
Before: https://main--cc--adobecom.hlx.page/creativecloud/video/hub/guides/avoid-continuity-errors-in-film?martech=off
After: https://main--cc--ruchika4.hlx.page/creativecloud/video/hub/guides/avoid-continuity-errors-in-film?martech=off

Add cc-shared new exclude path

---

creativecloud/scripts/scripts.js

Remove loadDelayed function from scripts.js 
https://jira.corp.adobe.com/browse/MWPW-131683
Slack discussion here https://adobe-mwp.slack.com/archives/C03B0BUA75E/p1684928927644169

remove loadDelayed

---

tools/sidekick/config.json

* Adds FG option to sidekick
Resolves: [MWPW-131688](https://jira.corp.adobe.com/browse/MWPW-131688)

MWPW-131688: FG Option in Sidekick

---

tools/sidekick/config.json

* Disable send to caas till the time feature mentioned in jira ticket is implemented
Needed to be done till this is resolved: [MWPW-132559](https://jira.corp.adobe.com/browse/MWPW-132559)
**Test URLs:**
NA

disable send to caas in config

---

creativecloud/scripts/scripts.js

Resolves: [MWPW-132823](https://jira.corp.adobe.com/browse/MWPW-132823)
**Test URLs:**
- After: https://salonijain3-patch-1--cc--adobecom.hlx.page/?martech=off

[MWPW-132823]DNS fix for fedpub pages

---

tools/sidekick/config.json

* Add OST in sidekick
Resolves: [MWPW-132855](https://jira.corp.adobe.com/browse/MWPW-132855)
**Test URLs:**
- After: https://ost-sidekick--cc--ruchika4.hlx.page/?martech=off

Add ost in sidekick plugin

---

creativecloud/scripts/scripts.js

* Add launch url and config for stage
Resolves: [MWPW-133943](https://jira.corp.adobe.com/browse/MWPW-133943)
**Test URLs:**
- Before: https://stage--cc--adobecom.hlx.page
- After: https://stage-launchUrl--cc--adobecom.hlx.page

Update launch url and config for stage

---

creativecloud/scripts/scripts.js

Add launch url and config for prod
Resolves: [MWPW-133943](https://jira.corp.adobe.com/browse/MWPW-133943)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page
- After: https://launch-config--cc--adobecom.hlx.page

Enable analytics on prod

---

tools/sidekick/config.json

* Add offer preview to sidekick
Resolves: [MWPW-132855](https://jira.corp.adobe.com/browse/MWPW-132855)
**Test URLs:**
NA

add offer preview to sidekick

---

creativecloud/scripts/scripts.js

* Add jarvis to config
Resolves: [MWPW-134634](https://jira.corp.adobe.com/browse/MWPW-134634)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/mena_ar/drafts/soujanya/academy-of-art-case-study?martech=off
- After: https://jarvis--cc--adobecom.hlx.page/mena_ar/drafts/soujanya/academy-of-art-case-study?martech=off

enable jarvis

---

helix-query.yaml

Resolves: [MWPW-135569](https://jira.corp.adobe.com/browse/MWPW-135569)
**Test URLs:**
NA

add robots in helix query

---

creativecloud/sitemap-index.xml
helix-query.yaml
helix-sitemap.yaml

* Add new geos to sitemap
Resolves: [MWPW-133043](https://jira.corp.adobe.com/browse/MWPW-133043)
**Test URLs:**
NA

Add sitemap for new geos

---

tools/loc/glaas.html
tools/loc/index.html
tools/loc/translation.css
tools/sidekick/config.json

- Adding html files for localization
Resolves: [MWPW-137590](https://jira.corp.adobe.com/browse/MWPW-137590)

Loc port for CC

---

404.html

* Load federated 404 page
Resolves: [MWPW-136654](https://jira.corp.adobe.com/browse/MWPW-136654)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/doesnotexist?martech=off
- After: https://stage-404--cc--adobecom.hlx.page/doesnotexist?martech=off

Load centralized 404 on stage.adobe.com

---

creativecloud/sitemap-index.xml
helix-query.yaml
helix-sitemap.yaml

* Set up sitemap for batch1A ROW
Resolves: [MWPW-133694](https://jira.corp.adobe.com/browse/MWPW-133694)
**Test URLs:**
- After: https://1Arow--cc--ruchika4.hlx.page/?martech=off

Sitemap for batch1A ROW

---

tools/sidekick/config.json

* Add OST in sidekick (stage branch)
Resolves: [MWPW-132855](https://jira.corp.adobe.com/browse/MWPW-132855)
**Test URLs:**
- After: https://ost-sidekick--cc--ruchika4.hlx.page/?martech=off

MWPW-132855-[Stage Branch]Add OST in sidekick

---

tools/sidekick/config.json

- Points to the new FG UI endpoint
Resolves: [MWPW-123360](https://jira.corp.adobe.com/browse/MWPW-123360)

MWPW-123360: Sidekick Update for new Floodgate endpoint

---

creativecloud/blocks/interactive-marquee/interactive-marquee.css
creativecloud/blocks/interactive-marquee/interactive-marquee.js
creativecloud/blocks/interactive-marquee/milo-marquee.css

* Implemented the base Interactive Marquee container for the upcoming variant - Genfill and Firefly
* Figma: https://www.figma.com/file/L1YpIBovlcXffNVvOePgA9/Interactive-Marquee-KR?type=design&node-id=56-1516&mode=design&t=URlCADx9xEuFjjuk-0
Resolves: [MWPW-138595](https://jira.corp.adobe.com/browse/MWPW-138595)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/drafts/drashti/MWPW-137345/container?martech=off
- After: https://stage--cc--drashti1712.hlx.page/drafts/drashti/MWPW-137345/container?martech=off

MWPW-137345 | [For Stage] Interactive container block for CC only

---

creativecloud/scripts/scripts.js

Fix stage libs out of sync from main | Causing failures in getLib

Fix stage libs out of sync from main | Causing failures in getLib

---

creativecloud/blocks/interactive-marquee/interactive-marquee.js
creativecloud/features/firefly/firefly-interactive.css
creativecloud/features/firefly/firefly-interactive.js
creativecloud/features/firefly/firefly-susi.js
creativecloud/features/interactive-elements/interactive-elements.css
creativecloud/features/interactive-elements/interactive-elements.js
creativecloud/scripts/scripts.js
creativecloud/scripts/utils.js
test/features/firefly/firefly-interactive.test.js
test/features/firefly/mocks/body.html

* Optimize code for firefly Interactive marquee
* Fixes some bugs found while testing (details can be seen in commits
* Also fixes the interactive container issue of not loading in safari when multiple interactive marquees added on a page.
Resolves: [MWPW-138426](https://jira.corp.adobe.com/browse/MWPW-138426)
**Test URLs:**
- Before: https://stage--cc--adobecom.hlx.live/drafts/ruchika/firefly/firefly-latest?martech=off
- After: https://stage-FF--cc--adobecom.hlx.live/drafts/ruchika/firefly/firefly-latest?martech=off
Performance: https://pagespeed.web.dev/analysis/https-stage-ff--cc--adobecom-hlx-live-drafts-ruchika-firefly-firefly-latest/4y8req1t7j?form_factor=mobile

MWPW-138426-Optimize code for firefly marquee

---

creativecloud/features/genfill/genfill-interactive.js
creativecloud/scripts/scripts.js

Resolves: [MWPW-139958](https://jira.corp.adobe.com/browse/MWPW-139958)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/drafts/drashti/MWPW-137345/final-genfill/psonline?martech=off
- After: https://stage-genfill--cc--adobecom.hlx.page/drafts/drashti/MWPW-137345/final-genfill/psonline?martech=off

[Genfill Marquee] MWPW-139958 - Analytics Tracking and Performance Optimization

---

404.html

* Load federated 404 page
Resolves: [MWPW-136654](https://jira.corp.adobe.com/browse/MWPW-136654)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/doesnotexist?martech=off
- After: https://central404--cc--adobecom.hlx.page/doesnotexist?martech=off

MWPW-136654-Add meta tag to load 404 from centralized place in milo

---

.github/workflows/run-lint.yaml
.github/workflows/run-tests.yaml
creativecloud/blocks/interactive-marquee/interactive-marquee.js
creativecloud/blocks/interactive-marquee/milo-marquee.css
creativecloud/features/firefly/firefly-interactive.css
creativecloud/features/firefly/firefly-interactive.js
creativecloud/features/firefly/firefly-susi.js
creativecloud/features/interactive-elements/interactive-elements.css
creativecloud/features/interactive-elements/interactive-elements.js
creativecloud/scripts/decorate.js
creativecloud/scripts/scripts.js
creativecloud/scripts/utils.js
test/blocks/firefly/firefly-interactive.test.js
test/blocks/firefly/mocks/body.html
test/helpers/waitForElement.js
web-test-runner-config.mjs

* This PR moves @drashti1712 's code for Interactive marquee container(interactive-marquee.js and milo-marquee.css) from stage to main
* Firefly Interactive marquee implementation
* git workflow update to separate unit test and lint check
* helper function for unit test to wait for element
* utils.js update to import getLibs
* scripts.js update for firefly interactive marquee
Resolves: [MWPW-138426](https://jira.corp.adobe.com/browse/MWPW-138426)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/drafts/ruchika/firefly/firefly-latest?martech=off
- After: https://main-ff--cc--adobecom.hlx.live/drafts/ruchika/firefly/firefly-latest?martech=off

MWPW-138426-Firefly Interactive Marquee

---

creativecloud/sitemap-index.xml

* Fix error when trying to submit sitemap to GSC
Resolves: [MWPW-140134](https://jira.corp.adobe.com/browse/MWPW-140134)
**Test URLs:**
NA

Fix error when trying to submit sitemap to GSC

---

creativecloud/features/changeBg/changeBg.js

Resolves: [MWPW-139735](https://jira.corp.adobe.com/browse/MWPW-139735)
**Test URLs:**
- After: https://changeStageBG--cc--suhjainadobe.hlx.live/drafts/suhjain/imarquee?martech=off

change background main

---

creativecloud/features/interactive-elements/interactive-elements.css

* Prompt bar and selector tray box-sizing css update
Resolves: [MWPW-140297](https://jira.corp.adobe.com/browse/MWPW-140297)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/drafts/jbrown/firefly/firefly?martech=off
- After: https://MWPW-140297--cc--adobecom.hlx.page/drafts/jbrown/firefly/firefly?martech=off

MWPW-140297- Set box-sizing for promptbar and selector tray in FF marquee

---

creativecloud/features/firefly/firefly-interactive.css
creativecloud/features/firefly/firefly-interactive.js

* Fix blinking cursor in iOS when georouting pop up shows as autofocus on prompt is lost
* Also fixes placeholder text color for safari and firefox
Resolves: [MWPW-140027](https://jira.corp.adobe.com/browse/MWPW-140027)
**Test URLs:**
- After: https://mwpw-140027--cc--adobecom.hlx.live/drafts/ruchika/firefly/remove-dnt/document1?martech=off

MWPW-140027-[FF IM]Fix blinking cursor in iOS when georouting pop up shows

---

creativecloud/blocks/sidenav/sidenav.js
test/blocks/sidenav/mocks/sidenav.html
test/blocks/sidenav/mocks/taxonomy.json
test/blocks/sidenav/sidenav.test.js

MWPW-137257
updated also the test page with some documentation :) 
https://mwpw-137257--cc--npeltier.hlx.page/drafts/npeltier/sidenav-test

MWPW-137257 adapt values to taxonomy

---

creativecloud/features/firefly/firefly-interactive.css
creativecloud/features/firefly/firefly-susi.js
creativecloud/features/interactive-elements/interactive-elements.css

* Implements RTL design for selector tray and enticement
* Fixes minor spacing issue mentioned in point 5 in jira ticket https://jira.corp.adobe.com/browse/MWPW-140669
* Also small code update to delete all query params on click of generate before setting new query params
Resolves: [MWPW-139604](https://jira.corp.adobe.com/browse/MWPW-139604)
**Test URLs:**
- After: https://rtl-ff--cc--adobecom.hlx.live/drafts/ruchika/firefly/remove-dnt/document1?martech=off
**Note:** First 2 point mentioned in the PR description have been verified with UX team on feature branch.

MWPW-139604-Implement RTL design for selector tray and enticement

---

creativecloud/scripts/scripts.js

* Add new geos to the locales in config
Resolves: [MWPW-140715](https://jira.corp.adobe.com/browse/MWPW-140715)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/ae_en/creativecloud/tools/app-design-software#langnav
- After: https://new-geos--cc--adobecom.hlx.live/ae_en/creativecloud/tools/app-design-software#langnav

[Stage]MWPW-140715-Add new geos to the locales in config

---

creativecloud/features/changeBg/author-feedback.css
creativecloud/features/changeBg/author-feedback.js
creativecloud/features/changeBg/changeBg.js
creativecloud/scripts/scripts.js

Resolves: [[MWPW-139795](https://jira.corp.adobe.com/browse/MWPW-139795)]
**Test URLs:**
- Before: https://main--cc--suhjainadobe.hlx.page/drafts/suhjain/in-marquee
- After: https://auhtorfeedback--cc--suhjainadobe.hlx.page/drafts/suhjain/in-marquee

Authorfeedback for interactive marquee

---

helix-sitemap.yaml

* Fix hreflang for GT
Resolves: [MWPW-141205](https://jira.corp.adobe.com/browse/MWPW-141205)
**Test URLs:**
NA

MWPW-141205- hreflang fix for GT

---

CODEOWNERS

Adding Codeowners file to CC repo
**Test URLs:**
- After: https://codeownersfile--cc--aishwaryamathuria.hlx.live/?martech=off

Adding Codeowners file to CC repo

---

creativecloud/scripts/scripts.js
creativecloud/scripts/utils.js

Resolves: [[MWPW-141038](https://jira.corp.adobe.com/browse/MWPW-141038)](https://jira.corp.adobe.com/browse/MWPW-141038)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/drafts/Shrinidhi/int-marquee
- After:  https://scriptchangebug--cc--suhjainadobe.hlx.live/drafts/Shrinidhi/int-marquee#

MWPW-141038: interactive marquee change bg util.js is not seen loading fine

---

creativecloud/blocks/sidenav/sidenav.js
test/blocks/sidenav/sidenav.test.html

also types presence does manage types display
Resolves: [MWPW-137257](https://jira.corp.adobe.com/browse/MWPW-137257)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/drafts/npeltier/sidenav-test?martech=off
- After: https://mwpw-137257--cc--npeltier.hlx.live/drafts/npeltier/sidenav-test?martech=off

MWPW-137257 make type title configurable

---

creativecloud/features/changeBg/author-feedback.js

* Fixing authoring feedback error
Resolves: [MWPW-141554](https://jira.corp.adobe.com/browse/MWPW-NUMBER)
**Test URLs:**
- Before: https://auhtorfeedback--cc--suhjainadobe.hlx.page/creativecloud/animation/discover/testdraftsfirefly/imarquee#
- After: https://feedbackauthor--cc--suhjainadobe.hlx.page/creativecloud/animation/discover/testdraftsfirefly/imarquee#

MWPW-141554: Fixing authoring feedback error

---

creativecloud/blocks/interactive-marquee/interactive-marquee.js
creativecloud/blocks/interactive-marquee/milo-marquee.css
creativecloud/features/firefly/firefly-interactive.css
creativecloud/features/firefly/firefly-interactive.js
creativecloud/features/firefly/firefly-susi.js
creativecloud/features/interactive-elements/interactive-elements.css
creativecloud/features/interactive-elements/interactive-elements.js
test/features/firefly/mocks/body.html

* Sync interactive marquee and FF marquee code from main to stage
**Test URLs:**
- Before: https://stage--cc--adobecom.hlx.live/drafts/ruchika/firefly/remove-dnt/document1?martech=off
- After: https://sync-stage--cc--adobecom.hlx.live/drafts/ruchika/firefly/remove-dnt/document1?martech=off

Sync interactive marquee and FF marquee code from main to stage

---

creativecloud/features/firefly/firefly-interactive.js
creativecloud/features/firefly/firefly-susi.js
creativecloud/scripts/scripts.js

* Fix to redirect user directly firefly product page from adobe.com page.
* We have updated allowed list for this in out client id too.
Resolves: [MWPW-140914](https://jira.corp.adobe.com/browse/MWPW-140914)
**Test URLs:**
- After: https://MWPW-140914--cc--adobecom.hlx.live/drafts/ruchika/firefly/remove-dnt/document1?martech=off
**Note:** This PR is same as https://github.com/adobecom/cc/pull/170/files which was merged in stage branch and tested

[main]MWPW-140914-Redirect user directly to firefly product page from firefly marketing page

---

helix-query.yaml
helix-sitemap.yaml

* Sitemaps for batch 1B ROW
Resolves: [MWPW-142331](https://jira.corp.adobe.com/browse/MWPW-142331)
**Test URLs:**
NA
Note: PR to sitemap-index file will be raised later and will be merged during the release.
This PR also moves the card indexing code from stage to main.

[Main]MWPW-142331-Batch1B ROW Sitemap

---

helix-query.yaml
helix-sitemap.yaml

* Sitemaps for batch 1B ROW
Resolves: [MWPW-142331](https://jira.corp.adobe.com/browse/MWPW-142331)
**Test URLs:**
NA
Note: PR to sitemap-index file will be raised later and will be merged during the release.

[Stage]MWPW-142331-Batch1B ROW Sitemap

---

helix-query.yaml
helix-sitemap.yaml

* Remove duplicate entry for za
Resolves: [MWPW-142331](https://jira.corp.adobe.com/browse/MWPW-142331)
**Test URLs:**
NA

MWPW-142331-Remove duplicate entry

---

helix-query.yaml
helix-sitemap.yaml

* Remove duplicate entry for za
Resolves: [MWPW-142331](https://jira.corp.adobe.com/browse/MWPW-142331
**Test URLs:**
NA

MWPW-142331-Remove duplicate entry (#182)

---

creativecloud/sitemap-index.xml
helix-query.yaml
helix-sitemap.yaml

* Fix issues found during testing
Resolves: [MWPW-143055](https://jira.corp.adobe.com/browse/MWPW-143055)
**Test URLs:**
NA

MWPW-143055-Fix issues found during testing

---

helix-query.yaml
helix-sitemap.yaml

* Fix issues identified in today's testing of sitemaps for batch 1B ROW
Resolves: [MWPW-143055](https://jira.corp.adobe.com/browse/MWPW-143055)
**Test URLs:**
NA

MWPW-143055-fix sitemap issues for batch 1B ROW

---

creativecloud/blocks/universal-promo-terms/universal-promo-terms.css
creativecloud/blocks/universal-promo-terms/universal-promo-terms.js
test/blocks/universal-promo-terms/mocks/body.html
test/blocks/universal-promo-terms/universal.promo.terms.test.js

Resolves: [MWPW-141444](https://jira.corp.adobe.com/browse/MWPW-141444)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/drafts/seanchoi/universal-promo-terms?offer_selector_ids=x-TQSF1eZiZ637gnd_GgfN1c7W0Ksj2FG7gJwxCHCjY&locale=en_US&promotion_code=COM_CCSN_STOCKPD&country=CY&service_providers=PROMO_TERMS&landscape=draft&martech=off
- After: https://universal-promo-terms--cc--adobecom.hlx.live/drafts/seanchoi/universal-promo-terms?offer_selector_ids=x-TQSF1eZiZ637gnd_GgfN1c7W0Ksj2FG7gJwxCHCjY&locale=en_US&promotion_code=COM_CCSN_STOCKPD&country=CY&service_providers=PROMO_TERMS&landscape=draft&martech=off

Universal promo terms

---

creativecloud/blocks/universal-promo-terms/universal-promo-terms.js

This will handles edge cases of stage as well.
Resolves: [MWPW-141444](https://jira.corp.adobe.com/browse/MWPW-141444)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/drafts/seanchoi/universal-promo-terms?offer_selector_ids=x-TQSF1eZiZ637gnd_GgfN1c7W0Ksj2FG7gJwxCHCjY&locale=en_US&promotion_code=COM_CCSN_STOCKPD&country=CY&service_providers=PROMO_TERMS&landscape=draft&martech=off
- After: https://universal-promo-terms--cc--adobecom.hlx.live/drafts/seanchoi/universal-promo-terms?offer_selector_ids=x-TQSF1eZiZ637gnd_GgfN1c7W0Ksj2FG7gJwxCHCjY&locale=en_US&promotion_code=COM_CCSN_STOCKPD&country=CY&service_providers=PROMO_TERMS&landscape=draft&martech=off

[Universal promo terms] update env logic

---

creativecloud/scripts/scripts.js

* Add cis_ru to locales in config
Resolves: [MWPW-143631](https://jira.corp.adobe.com/browse/MWPW-143631)
**Test URLs:**
NA

MWPW-143631-Add cis_ru to locales

---

creativecloud/scripts/scripts.js

* Add cis_ru to locales in config
Resolves: [MWPW-143631](https://jira.corp.adobe.com/browse/MWPW-143631)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/cis_ru/drafts/Souj/test-offers-page?martech=off
- After: https://new-locale--cc--adobecom.hlx.page/cis_ru/drafts/Souj/test-offers-page?martech=off
Note: this has been tested and verified and merged in stage branch. Stage PR: https://github.com/adobecom/cc/pull/199
However facing issue with raising PR from stage to main because of some some mismatch git commit history. And as this ticket is blocker and needs to get merged in main asap hence raising PR from separate branch. Code change is same that has been tested and can be verified from the stage branch.

[Main]MWPW-143631-Add cis_ru to locales

---

creativecloud/scripts/scripts.js

Resolves: 
- https://jira.corp.adobe.com/browse/MWPW-143631
- https://jira.corp.adobe.com/browse/MWPW-140666
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/cis_en/products/special-offers
- After: https://cisen--cc--adobecom.hlx.live/cis_en/products/special-offers

MWPW-140666: add cis_en to locales

---

helix-sitemap.yaml

This reverts commit f0c12bcd9e0050cf5ff80d6c56511d9032ada201.

Revert accidental direct commit

---

creativecloud/blocks/universal-promo-terms/universal-promo-terms.js

Revert "Universal promo terms"

---

creativecloud/scripts/scripts.js

* Add cis_en
Resolves: [MWPW-143631](https://jira.corp.adobe.com/browse/MWPW-143631)
**Test URLs:**
NA

MWPW-143631-Add cis_en to config

---

creativecloud/blocks/universal-promo-terms/universal-promo-terms.js

Resolves: [MWPW-143792](https://jira.corp.adobe.com/browse/MWPW-143792)
Test URLs:
Before: https://main--cc--adobecom.hlx.page/offers/promo-terms?locale=jp_JP&promotion_code=JCB_ABM_35&country=US&offer_id=7688344A06D9465C258D864506C82AE6&martech=off
After: https://universal-promo-terms--cc--adobecom.hlx.page/offers/promo-terms?locale=jp_JP&promotion_code=JCB_ABM_35&country=US&offer_id=7688344A06D9465C258D864506C82AE6&martech=off

[MWPW-143792] Fixing bug on UPT

---

helix-query.yaml
helix-sitemap.yaml

- add sitemaps index config for CIS_RU and CIS_EN
- add missing cards index definitions for a number of geos
Resolves: https://jira.corp.adobe.com/browse/MWPW-140666 
**Test URLs:**
N/A

add cis sitemaps index

---

helix-query.yaml
helix-sitemap.yaml

add https://github.com/adobecom/cc/pull/205 to main

[MAIN] add cis sitemaps (#205)

---

creativecloud/sitemap-index.xml
helix-query.yaml

Resolves: https://jira.corp.adobe.com/browse/MWPW-140666

[Stage] add products to index

---

creativecloud/sitemap-index.xml
helix-query.yaml

https://jira.corp.adobe.com/browse/MWPW-140666

[Main] add Products to sitemap index

---

creativecloud/blocks/universal-promo-terms/universal-promo-terms.js
creativecloud/scripts/scripts.js

Sync main from stage for final stage rebase
Merging following PRs -
https://github.com/adobecom/cc/pull/211
https://github.com/adobecom/cc/pull/212

Sync main from stage for final stage rebase

---

creativecloud/scripts/utils.js

* Update all media paths to load from content root
Resolves: [MWPW-142577](https://jira.corp.adobe.com/browse/MWPW-142577)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/careers?martech=off
- After: https://mwpw-142577--cc--adobecom.hlx.live/careers?martech=off

MWPW-142577-Update all media paths to load from content root

---

.github/workflows/log-previews.yml

Print the event payload to extract the previewed path details
Resolves: [MWPW-144005](https://jira.corp.adobe.com/browse/MWPW-144005)
**Test URLs:**
- After: https://test-preview--cc--adobecom.hlx.page/?martech=off

MWPW-144005 For testing print event payload

---

creativecloud/features/firefly/firefly-interactive.css

* Fix selector tray alignment
Resolves: [MWPW-144477](https://jira.corp.adobe.com/browse/MWPW-144477)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/drafts/ruchika/ff-selectortray?martech=off
- After: https://firefly-selectortray--cc--adobecom.hlx.live/drafts/ruchika/ff-selectortray?martech=off
With 3 options:
- After: https://firefly-selectortray--cc--adobecom.hlx.live/drafts/ruchika/firefly/remove-dnt/document1?martech=off

MWPW-144477-Fix selector tray alignment

---

codecov.yaml
package.json
web-test-runner.config.mjs

* Fixing the code coverage plugin path
Resolves: [MWPW-144525](https://jira.corp.adobe.com/browse/MWPW-144525)
**Test URLs:**
- After: https://codecov--cc--aishwaryamathuria.hlx.live/?martech=off

MWPW-144525 | Fixing the code coverage plugin path

---

helix-query.yaml

* Update helix-query.yaml to include /ai/* path in sitemap
Resolves: [MWPW-144599](https://jira.corp.adobe.com/browse/MWPW-144599)
**Test URLs:**
NA

MWPW-144599-Include /ai/** path in sitemap

---

creativecloud/blocks/interactive-marquee/interactive-marquee.js
creativecloud/scripts/utils.js

* Improve performance and reduce CLS for interactive marquee
Resolves: [MWPW-144479](https://jira.corp.adobe.com/browse/MWPW-144479)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/drafts/ruchika/3a/firefly?martech=off
- After: https://mwpw-144479--cc--aishwaryamathuria.hlx.live/drafts/ruchika/3a/firefly?martech=off

MWPW 144479 | Improve performance and reduce CLS for interactive marquee

---

creativecloud/features/firefly/firefly-interactive.css
creativecloud/sitemap-index.xml
helix-query.yaml
helix-sitemap.yaml

* This PR has following PR from stage
https://github.com/adobecom/cc/pull/223
https://github.com/adobecom/cc/pull/222
https://github.com/adobecom/cc/pull/231
**Test URLs:**
- After: https://sync-main--cc--adobecom.hlx.page/?martech=off

Sync main with stage

---

creativecloud/scripts/utils.js

**Test URLs:**
- After: https://<branch>--cc--adobecom.hlx.page/?martech=off

Revert mwpw 142577

---

creativecloud/blocks/interactive-metadata/interactive-metadata.css
creativecloud/blocks/interactive-metadata/interactive-metadata.js
creativecloud/features/interactive-components/generate/generate.css

Dev PR - Merging between two dev branches

Dev PR - Merging between two dev branches 

---

creativecloud/scripts/utils.js

Improve performance and reduce CLS for interactive marquee
Stage Merged PR: https://github.com/adobecom/cc/pull/237
Resolves: [MWPW-144479](https://jira.corp.adobe.com/browse/MWPW-144479)
Test URLs:
Before: https://main--cc--adobecom.hlx.live/drafts/ruchika/3a/firefly?martech=off
After: https://stage--cc--adobecom.hlx.live/drafts/ruchika/3a/firefly?martech=off

[Release] Sync main from stage 20/3/2024

---

README.md

PR to add details of CC code merge process in Readme

Stage | PR to add details of CC code merge process in Readme

---

creativecloud/blocks/interactive-metadata/interactive-metadata.css
creativecloud/blocks/interactive-metadata/interactive-metadata.js
creativecloud/features/interactive-components/generate/generate.css
creativecloud/features/interactive-components/start-over/start-over.css
creativecloud/features/interactive-components/start-over/start-over.js
creativecloud/styles/styles.css

*  animations, aside and other changes for generate prompt and start over button
Resolves: [MWPW-142980](https://jira.corp.adobe.com/browse/MWPW-142980)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/drafts/drashti/genfill-aside/document3?martech=off
- After: https://imtd-animation--cc--adobecom.hlx.page/drafts/drashti/genfill-aside/document3?martech=off

<Ignore> Dev branch PR Genfill aside: Generate and start-over changes [from imtd-animation branch]

---

creativecloud/features/genfill/genfill-interactive.css
creativecloud/features/interactive-elements/interactive-elements.css
creativecloud/features/interactive-elements/interactive-elements.js

* Move enticement text to p tag
Resolves: [MWPW-145307](https://jira.corp.adobe.com/browse/MWPW-145307)
**Test URLs:**
- Before: https://stage--cc--adobecom.hlx.live/drafts/drashti/MWPW-137345/genfill-container?martech=off
- After: https://enticement-text--cc--adobecom.hlx.live/drafts/drashti/MWPW-137345/genfill-container?martech=off
Firefly marquee
- Before: https://stage--cc--adobecom.hlx.live/drafts/ruchika/firefly/remove-dnt/document1?martech=off
- After: https://enticement-text--cc--adobecom.hlx.live/drafts/ruchika/firefly/remove-dnt/document1?martech=off

MWPW-145307- Move enticement text to p tag

---

creativecloud/scripts/utils.js

* Load all media of embedded media for root pages from relate content root paths.
Resolves: [MWPW-142577](https://jira.corp.adobe.com/browse/MWPW-142577)
Test URLs:
After: https://mwpw-142577--cc--aishwaryamathuria.hlx.live/careers?martech=off

MWPW-142577 | Load media from cc-shared for root

---

creativecloud/blocks/interactive-metadata/interactive-metadata.js

* Improving performance for hue sat
Resolves: [MWPW-146221](https://jira.corp.adobe.com/browse/MWPW-146221)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/drafts/mathuria/interactiveelems/demo/huesat/hue-sat-marquee1?martech=off
- After: https://mwpw-146221--cc--aishwaryamathuria.hlx.live/drafts/mathuria/interactiveelems/demo/huesat/hue-sat-marquee1?martech=off

MWPW-146221 | Improving performance for hue sat

---

.github/workflows/graybox-sync-repos.yml

* Enable CC repo-sync for CC graybox repo
Resolves: [MWPW-142006](https://jira.corp.adobe.com/browse/MWPW-142006)

MWPW-142006 - Enable repo-sync for graybox

---

creativecloud/blocks/catalog/catalog.css
creativecloud/blocks/catalog/catalog.js
creativecloud/blocks/sidenav/sidenav.js
creativecloud/deps/merch-sidenav.js
creativecloud/scripts/scripts.js

move merch-card-collection and sidenav inside
catalog block.
includes: https://git.corp.adobe.com/wcms/tacocat.js/pull/552/files
depends on: https://github.com/adobecom/milo/pull/2057
Resolves: [MWPW-143951](https://jira.corp.adobe.com/browse/MWPW-143951)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/drafts/ilyas/catalog-sidenav?martech=off&georouting=off
- After: https://mwpw-143951--cc--yesil.hlx.live/drafts/ilyas/catalog?martech=off&georouting=off

MWPW-143951: Optimize sidenav

---

creativecloud/features/interactive-components/slider-tray/slider-tray.css
creativecloud/features/interactive-components/slider-tray/slider-tray.js

[hue saturation] upload image icon authored is not seen visible in mobile mode
Resolves: [MWPW-146219](https://jira.corp.adobe.com/browse/MWPW-146219)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/drafts/suhjain/document7?martech=off
- After: https://mwpw-146219--cc--adobecom.hlx.live/drafts/suhjain/document7?martech=off

[hue saturation] upload image icon authored is not seen visible in mobile mode

---

creativecloud/blocks/interactive-metadata/interactive-metadata.js
creativecloud/features/interactive-components/start-over/start-over.js

Integrating review comments for delay authoring of Start over button. 0-99 will be considered as sec and 99+ will be ms
Resolves: [MWPW-142972](https://jira.corp.adobe.com/browse/MWPW-142972)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/drafts/mathuria/interactiveelems/interactive-workflow4?martech=off
- After: https://mwpw-142972--cc--aishwaryamathuria.hlx.live/drafts/mathuria/interactiveelems/interactive-workflow4?martech=off?martech=off

MWPW-142972 | Integrating review comments

---

creativecloud/blocks/cc-mobile-app-banner/cc-mobile-app-banner.css
creativecloud/blocks/cc-mobile-app-banner/cc-mobile-app-banner.js
creativecloud/scripts/utils.js
test/blocks/cc-mobile-app-banner/cc-mobile-app-banner.test.js
test/blocks/cc-mobile-app-banner/mocks/body.html
test/blocks/cc-mobile-app-banner/mocks/branch-io-key.json
test/helpers/waitForElement.js

* New block to allow authors to add branch io app banner
[Authoring documentation](https://stage--cc--adobecom.hlx.page/docs/authoring/cc-mobile-app-banner?martech=off)
Resolves: [MWPW-143904](https://jira.corp.adobe.com/browse/MWPW-143904)
**Test URLs:**
- Before: https://stage--cc--adobecom.hlx.live/drafts/ruchika/app-banner/photoshop-lightroom3?martech=off
- After: https://mobile-app-banner--cc--adobecom.hlx.live/drafts/ruchika/app-banner/photoshop-lightroom3?martech=off

MWPW-143904-New block: cc-mobile-app-banner

---

creativecloud/scripts/scripts.js

Revert "DOTCOM-118347" as it is not verified and has issues

Revert "DOTCOM-118347" as it is not verified and has issues

---

creativecloud/features/firefly/firefly-susi.js

* Update firefly model to v3
Resolves: [MWPW-147361](https://jira.corp.adobe.com/browse/MWPW-147361)
**Test URLs:**
- Before: https://stage--cc--adobecom.hlx.live/drafts/ruchika/firefly/remove-dnt/document1?martech=off
- After: https://firefly-model3--cc--adobecom.hlx.live/drafts/ruchika/firefly/remove-dnt/document1?martech=off

MWPW-147361-Update firefly model to v3

---

creativecloud/blocks/interactive-metadata/interactive-metadata.js

* Adding new workflow to enable new illustrator authoring.
Resolves: [MWPW-142971](https://jira.corp.adobe.com/browse/MWPW-142971)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/drafts/mathuria/interactiveelems/demo/handoff/totebag/totebag-selector-update?martech=off
- After: https://illustrator--cc--adobecom.hlx.live/drafts/mathuria/interactiveelems/demo/handoff/totebag/totebag-selector-update?martech=off

MWPW-142971 | Add new workflow for generate->select->startover

---

creativecloud/features/firefly/firefly-masonry.js

* Move image span value outside of alt value
Resolves: [MWPW-147905](https://jira.corp.adobe.com/browse/MWPW-147905)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/drafts/ruchika/firefly/take2/marquee8?martech=off
- After: https://image-span--cc--adobecom.hlx.live/drafts/ruchika/firefly/take2/marquee8?martech=off

MWPW-147905-Move image span value outside of alt value

---

creativecloud/features/firefly/firefly-masonry.js

* Fix Generate button in multi image marquee
Resolves: [MWPW-148147](https://jira.corp.adobe.com/browse/MWPW-148147)
**Test URLs:**
- Before: https://stage--cc--adobecom.hlx.live/drafts/ruchika/firefly/take2/marquee8?martech=off
- After: https://MWPW-148147--cc--adobecom.hlx.live/drafts/ruchika/firefly/take2/marquee8?martech=off

MWPW-148147-Fix Generate button

---

creativecloud/blocks/interactive-metadata/interactive-metadata.js
creativecloud/features/interactive-components/redirect/redirect.css
creativecloud/features/interactive-components/redirect/redirect.js

**Test URLs:**
- Before: https://unity--cc--adobecom.hlx.live/?martech=off
- After: https://unity-poc-direct--cc--adobecom.hlx.live/?martech=off

Unity poc redirect

---

creativecloud/blocks/interactive-metadata/interactive-metadata.js
creativecloud/blocks/unity/unity.js
creativecloud/features/interactive-components/compress/compress.css
creativecloud/features/interactive-components/compress/compress.js

* POC for Compress PDF feature
**Test URLs:**
- Before: https://unity--cc--adobecom.hlx.live/?martech=off
- After: https://unity-poc-compress-pdf--cc--adobecom.hlx.live/?martech=off

Unity poc compress PDF

---

.github/workflows/merged-to-main.yaml

TEST | [Release] Stage to Main 

---

creativecloud/features/interactive-components/removebg/removebg.js

**Test URLs:**
- Before: https://unity--cc--adobecom.hlx.page/drafts/ruchika/unity/interactive-removebg?martech=off
- After: https://bg-upload--cc--adobecom.hlx.page/drafts/ruchika/unity/interactive-removebg?martech=off

fix upload image for split marquee

---

.github/workflows/merged-to-main.yaml

TEST | Release

---

.github/workflows/merged-to-main.yaml

PR for release notes testing

---

.github/workflows/merged-to-main.yaml
.github/workflows/src/helpers.js
.github/workflows/src/send-slack.js

TEST |
Release notes of this PR

TEST | Release 

---

.github/workflows/merged-to-main.yaml

check for testing

---

.github/workflows/merged-to-main.yaml

Final code from mwpw-140115 & removed condition for testing

TEST | Final Code

---

creativecloud/scripts/scripts.js

* Update thai pages to load Adobe Clean Thai
Resolves: [MWPW-130601](https://jira.corp.adobe.com/browse/MWPW-130601)
**Test URLs:**
- Before: https://stage--cc--adobecom.hlx.live/th_th/drafts/ruchika/thai-page?martech=off&georouting=off
- After: https://thai-typekit--cc--adobecom.hlx.live/th_th/drafts/ruchika/thai-page?martech=off&georouting=off

MWPW-130601-Add typekit for adobe clean thai

---

creativecloud/scripts/utils.js

Resolves: [MWPW-151792](https://jira.corp.adobe.com/browse/MWPW-151792)
**Test URLs:**
- Before: https://stage--cc--adobecom.hlx.live/careers?martech=off
- After: https://acomsis-cookie--cc--adobecom.hlx.live/careers?martech=off
This is the follow up PR for https://github.com/adobecom/cc/pull/321
This is for fixing bug after testing the logic stage.adobe.com

Fixing infinity reload bug

---

creativecloud/scripts/utils.js

Found a typo that creates a bug from https://github.com/adobecom/cc/pull/337
Resolves: [MWPW-151792](https://jira.corp.adobe.com/browse/MWPW-151792)
Test URLs:
Before: https://stage--cc--adobecom.hlx.live/careers?martech=off
After: https://acomsis-cookie--cc--adobecom.hlx.live/careers?martech=off

Acomsis cookie

---

helix-query.yaml

* add new paths to include list for indexing
Resolves: [MMWPW-152553](https://jira.corp.adobe.com/browse/MWPW-152553)
[MWPW-144603](https://jira.corp.adobe.com/browse/MWPW-144603)
**Test URLs:**
- Before: https://stage--cc--adobecom.hlx.live/drafts/ruchika/test?martech=off
- After: https://sitemap--cc--adobecom.hlx.live/drafts/ruchika/test?martech=off

MWPW-152553- Include new paths for indexing

---

helix-query.yaml

- https://github.com/adobecom/cc/pull/341
**Test URLs:**
After: https://stage--cc--adobecom.hlx.live/careers?martech=off

[Release] Sync main from stage 6/14 (#341)

---

creativecloud/scripts/utils.js

Pre-load Marquee image if the marquee is getting replaced in MEP
Resolves: [MWPW-153144](https://jira.corp.adobe.com/browse/MWPW-NUMBER)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/drafts/suhjain/personalization/document
- After: https://eagerloadimg--cc--adobecom.hlx.live/drafts/suhjain/personalization/document?mep=off&martech=off
Screenshot of performance improvement:
Before:
After:

MWPW-153144 Pre-load Marquee image if the marquee is getting replaced in MEP

---

creativecloud/scripts/utils.js

Pre-load Marquee image if the marquee is getting replaced in MEP
Resolves: [MWPW-153144](https://jira.corp.adobe.com/browse/MWPW-153144)
Test URLs:
Before: https://main--cc--adobecom.hlx.page/drafts/suhjain/personalization/document
After: https://eagerloadinglcp--cc--adobecom.hlx.live/drafts/suhjain/personalization/document?mep=off&martech=off

MWPW-153144 | Fix issue in utils check queryselector

---

.github/workflows/merged-to-main.yaml
.github/workflows/src/helpers.js
.github/workflows/src/send-slack.js
package-lock.json
package.json

* Integrated `Slack Block Kit` format
* Added the `@octokit/rest` package for GitHub API.
* Enhanced the parsing input text and convert it into Slack block format.
Resolves: [MWPW-140115](https://jira.corp.adobe.com/browse/MWPW-140115)
Note: No impact on cc pages
**Test URLs:**
- Before: https://main--cc--sivasadobe.hlx.live/creativecloud?martech=off
- After: https://mwpw-140115--cc--sivasadobe.hlx.live/creativecloud?martech=off

MWPW-140115 Release notes on slack channel when PR merged with Main branch

---

.github/workflows/merged-to-main.yaml
.github/workflows/src/helpers.js
.github/workflows/src/send-slack.js
creativecloud/blocks/catalog/catalog.js
creativecloud/blocks/sidenav/sidenav.js
creativecloud/scripts/utils.js
creativecloud/styles/styles.css
package-lock.json
package.json
tools/sidekick/config.json

* Merging following PRs to main -
- https://github.com/adobecom/cc/pull/346
- https://github.com/adobecom/cc/pull/343
- https://github.com/adobecom/cc/pull/345
- https://github.com/adobecom/cc/pull/349
- https://github.com/adobecom/cc/pull/350
- https://github.com/adobecom/cc/pull/347
- https://github.com/adobecom/cc/pull/331
**Test URLs:**
After: https://stage--cc--adobecom.hlx.live/careers?martech=off

[Release] Sync main from stage 7/9

---

creativecloud/features/interactive-elements/interactive-elements.js
creativecloud/scripts/mep/aexg4866/firefly/firefly-masonry.js
creativecloud/scripts/mep/aexg4866/interactive-marquee/interactive-marquee.css
creativecloud/scripts/mep/aexg4866/interactive-marquee/interactive-marquee.js

* Test version of interactive marquee for express web app (add express variant)
* Rollout is likely to be a new block, so unnecessary code (variants not used for the test) has been removed. 
Resolves: [OPT-27991](https://jira.corp.adobe.com/browse/OPT-27991)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/products/firefly/features/text-to-image?mep=%2Fcc-shared%2Ffragments%2Ftests%2F2024%2Fq3%2Faexg4866%2Faexg4866.json--target-var1-newmarquee&target=off
- After: https://aexg4866--cc--adobecom.hlx.live/products/firefly/features/text-to-image?mep=%2Fcc-shared%2Ffragments%2Ftests%2F2024%2Fq3%2Faexg4866%2Faexg4866.json--target-var1-newmarquee&target=off

OPT-27991 AEXG4866 - AX take over of FF T2i SEO page

---

creativecloud/scripts/scripts.js

MWPW-154660 - remove marTechUrl and edgeConfigId for performance improvements
Resolves: [MWPW-154660](https://jira.corp.adobe.com/browse/MWPW-154660)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/careers?martech=off
- After: https://stage--cc--bbythewa.hlx.live/careers?martech=off

MWPW-154660 - remove marTechUrl and edgeConfigId for performance improvements

---

creativecloud/blocks/unity/unity.css
creativecloud/blocks/unity/unity.js
creativecloud/scripts/scripts.js

Adding unity block in CC
Resolves: [MWPW-154549](https://jira.corp.adobe.com/browse/MWPW-154549)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/drafts/mathuria/unity/poc?unitylibs=stage&martech=off
- After: https://mwpw-154549--cc--adobecom.hlx.live/drafts/mathuria/unity/poc?unitylibs=stage&martech=off

MWPW-154549 | Integrating unity Block in CC

---

creativecloud/features/interactive-components/generate/generate.css

* Fixed the generate button alignment on iPad
Resolves: [MWPW-154422](https://jira.corp.adobe.com/browse/MWPW-154422)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/drafts/Souj/interactivelements/demo/totebag-selector-update?martech=off
- After: https://mwpw-154422--cc--drashti1712.hlx.live/drafts/Souj/interactivelements/demo/totebag-selector-update?martech=off

[MWPW-154422] generate button is seen moved out of the screen in ipad - bug fix

---

.github/workflows/merge-to-stage.js

The Prs must contain the verified label before they can be merged to stage branch.
Resolves: [MWPW-154091](https://jira.corp.adobe.com/browse/MWPW-154091)
Test URLs:
Before: https://main--cc--adobecom.hlx.live/?martech=off
After: https://mwpw-154091--cc--sharath-kannan.hlx.live/?martech=off

Feat(MWPW-154091):Prs must contain verified label.

---

helix-query.yaml

* Added /downloads/ path in helix query
* locales mt and cy_en are redirected to ie
Resolves: [MWPW-153994](https://jira.corp.adobe.com/browse/MWPW-153994)
**Test URLs:**
- Before: https://stage--cc--adobecom.hlx.live/?martech=off
- After: https://sitemap-00c--cc--drashti1712.hlx.live/?martech=off

[MWPW-153994] Update helix query for sitemaps - Batch 00C

---

creativecloud/scripts/utils.js

Support hero-marquee eager loading of images in cc
Resolves: [MWPW-155908](https://jira.corp.adobe.com/browse/MWPW-155908)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/drafts/suhjain/document31
- After: https://eagerloadheromarquee--cc--adobecom.hlx.live/drafts/suhjain/document31

MWPW-155908 Support hero-marquee eager loading of images in cc

---

creativecloud/blocks/interactive-metadata/interactive-metadata.css
creativecloud/blocks/interactive-metadata/interactive-metadata.js

* Add new workflow to support premiere pro page
Resolves: [MWPW-155183](https://jira.corp.adobe.com/browse/MWPW-155183)
**Test URLs:**
Aside:
- Before: https://stage--cc--adobecom.hlx.live/drafts/ruchika/premiere-pro-aside?martech=off
- After: https://start-over--cc--adobecom.hlx.live/drafts/ruchika/premiere-pro-aside?martech=off
Marquee:
- Before: https://stage--cc--adobecom.hlx.live/drafts/ruchika/premiere-pro?martech=off
- After: https://start-over--cc--adobecom.hlx.live/drafts/ruchika/premiere-pro?martech=off

MWPW-155183 - Add new workflow to support premiere pro page

---

helix-query.yaml

* Add paths for batch20 to sitemap
Resolves: [MWPW-155626](https://jira.corp.adobe.com/browse/MWPW-155626)
**Test URLs:**
- After: https://career--cc--adobecom.hlx.live/?martech=off

[MWPW-155626] Add paths for batch20 to sitemap

---

.github/workflows/merge-to-stage.yaml

* The action is scheduled to run at 0 minutes past the hour, every 4 hours, Monday through Thursday.
Resolves: [MWPW-156143](https://jira.corp.adobe.com/browse/MWPW-156143)
**Test URLs:**
- After: https://mwpw-156143--cc--sharath-kannan.hlx.live/?martech=off

Fix(MWPW-156143):The action is scheduled to run from Monday through Thursday.

---

creativecloud/blocks/catalog/catalog.js

together with milo change allow easier keyboard browsing of catalog page (before that change one needs to browse through all the cards before getting to the filters) to get to final working accessibilty 
**Test URLs:**
- After: https://mwpw-156262--cc--npeltier.hlx.live/?martech=off

MWPW-156262 flip sidenav and merch-collection order

---

.github/preview-index/src/indexFull.js
.github/preview-index/src/indexSingle.js
.github/preview-index/src/sharepoint.js

* Index file needs to be previewed after it is updated.
Resolves: [MWPW-155686](https://jira.corp.adobe.com/browse/MWPW-155686)
**Test URLs:**
- After: https://mwpw155686preview3--cc--bozojovicic.hlx.live/?martech=off

MWPW-155686 Catalog Milo: Preview Index Follow Up

---

creativecloud/features/interactive-components/generate/generate.css
creativecloud/features/interactive-components/generate/generate.js
test/features/interactive-components/generate/mocks/body.html

This is to include a label that sits above the generate bar on the interactive marquee. This label should include an authorable icon and text. 
Resolves: [MWPW-147305](https://jira.corp.adobe.com/browse/MWPW-NUMBER)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/drafts/suhjain/interactive-marquee/nothern-lights?martech=off
- After: https://generatelabelnew--cc--suhjainadobe.hlx.live/drafts/suhjain/interactive-marquee/nothern-lights?martech=off

MWPW-147305 Adding generative pattern label to generate bar on Interactive Marquee

---

creativecloud/blocks/catalog/catalog.js

This reverts commit 2024400486a0e2a01410ba1152765eb9b34c10dc.
**Test URLs:**
- After: https://revert-change-4-migration--cc--npeltier.hlx.live/?martech=off

Revert "MWPW-156262 flip sidenav and merch-collection order (#392)"

---

creativecloud/blocks/catalog/catalog.js

allow easier keyboard browsing of catalog page 
Test URLs:
Before: https://main--cc--adobecom.hlx.live/?martech=off
After: https://mwpw-157468--cc--npeltier.hlx.live/?martech=off

MWPW-157468 flipping again sidenav and collection

---

creativecloud/blocks/interactive-metadata/interactive-metadata.js

* Video handling for premiere
Resolves: [MWPW-159014](https://jira.corp.adobe.com/browse/MWPW-159014)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/products/premiere?milolibs=marquee-cls--milo--mokimo&martech=off
- After: https://videochange--cc--adobecom.hlx.live/products/premiere?milolibs=marquee-cls--milo--mokimo&martech=off

MWPW-159014 | Video handling for premiere

---

README.md

[Test]Update README.md

---

creativecloud/blocks/interactive-metadata/interactive-metadata.css

* Rearrange content in mobile view for marquee used with interactive metadata
Resolves: [MWPW-159151](https://jira.corp.adobe.com/browse/MWPW-159151)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/drafts/ruchika/mobile/illustrator2?martech=off
- After: https://mobile--cc--adobecom.hlx.live/drafts/ruchika/mobile/illustrator2?martech=off

[MWPW-159151] Rearrange content in mobile view for marquee used with interactive metadata

---

README.md

Reverts adobecom/cc#415
**Test URLs:**
- Before: https://stage--cc--adobecom.hlx.live/careers?martech=off
- After: https://revert-415-test--cc--adobecom.hlx.live/careers?martech=off

Revert "[Test]Update README.md"

---

test/scripts/mocks/head.html
test/scripts/scripts.test.js

* Unit test fix
Resolves: [MWPW-159309](https://jira.corp.adobe.com/browse/MWPW-159309)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/careers?martech=off
- After: https://utfix--cc--adobecom.hlx.live/careers?martech=off

MWPW-159309 | Unit test fix

---

README.md
creativecloud/blocks/interactive-metadata/interactive-metadata.css
test/scripts/mocks/head.html
test/scripts/scripts.test.js

- https://github.com/adobecom/cc/pull/417
- https://github.com/adobecom/cc/pull/420
**Creative cloud:**
- After: https://stage--cc--adobecom.hlx.live/?martech=off

[Release] Stage to Main 09/27

---

creativecloud/blocks/nonprofit/nonprofit.css
creativecloud/blocks/nonprofit/nonprofit.js
package.json
test/blocks/nonprofit/nonprofit.test.js
web-test-runner.config.mjs

* Adds Legal urls replacement and accessibility link underline
Resolves: [MWPW-160858](https://jira.corp.adobe.com/browse/MWPW-160858)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/drafts/rivero/nonprofits?martech=off
- After live: https://mwpw-160858--cc--adobecom.hlx.live/drafts/rivero/nonprofits?martech=off

MWPW-160858: [Nonprofits] Update Link Destinations

---

creativecloud/features/cc-forms/components/progress-circle.css
creativecloud/features/cc-forms/forms/trials.js

* Added a circle loader for cc-forms block
Resolves: [MWPW-163000](https://jira.corp.adobe.com/browse/MWPW-163000)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/drafts/drashti/dalpforms/perpeptual?martech=off
- After: https://dalp-loader--cc--adobecom.hlx.live/drafts/drashti/dalpforms/perpeptual?martech=off

[MWPW-163000] Add circle loader to PPBU forms

---

creativecloud/blocks/cc-forms/cc-forms.css
creativecloud/features/cc-forms/components/checkbox.js
creativecloud/features/cc-forms/components/dropdown.js
creativecloud/features/cc-forms/components/textfield.js
creativecloud/features/cc-forms/forms/connecttrials.js

Dalp forms

---

creativecloud/blocks/cc-forms/cc-forms.js

Default spacing

---

creativecloud/blocks/cc-forms/cc-forms.js
creativecloud/features/cc-forms/forms/connect.js

connect trials form

---

creativecloud/features/cc-forms/forms/connect.js

img changes in coonect

---

creativecloud/features/cc-forms/forms/perpeptual.js

Redirect setting

---

helix-query.yaml

* sitemap update for new batches
Resolves: [MWPW-160465](https://jira.corp.adobe.com/browse/MWPW-160465)
[MWPW-160723](https://jira.corp.adobe.com/browse/MWPW-160723)
[MWPW-161245](https://jira.corp.adobe.com/browse/MWPW-161245)
[MWPW-161406](https://jira.corp.adobe.com/browse/MWPW-161406)
[MWPW-161416](https://jira.corp.adobe.com/browse/MWPW-161416)
[MWPW-162397](https://jira.corp.adobe.com/browse/MWPW-162397)
**Test URLs:**
- After: https://site-map--cc--adobecom.hlx.live/?martech=off

MWPW-160465-sitemap update for new batches

---

creativecloud/features/cc-forms/forms/perpeptual.js

changing the function

---

creativecloud/blocks/nonprofit/nonprofit.js
test/blocks/nonprofit/nonprofit.test.js

- Adding email localization for non profits block
Resolves: [MWPW-163170](https://jira.corp.adobe.com/browse/MWPW-163170)
Test URLs:
Before: https://main--cc--adobecom.hlx.live/nonprofits/apply?martech=off
After: https://mwpw-163170--cc--adobecom.hlx.live/nonprofits/apply?martech=off

MWPW-163170: Non-profits - Adding email localization

---

creativecloud/features/cc-forms/forms/perpeptual.js

Download fix

---

creativecloud/blocks/nonprofit/nonprofit.js

- Switching to registryId to improve UX
Resolves: [MWPW-163072](https://jira.corp.adobe.com/browse/MWPW-163072)
Test URLs:
Before: https://main--cc--adobecom.hlx.live/nonprofits/apply?martech=off
After: https://mwpw-163072--cc--adobecom.hlx.live/nonprofits/apply?martech=off

MWPW-163072: Showing registryId to users easily find their organization

---

creativecloud/blocks/unity/unity.js
creativecloud/scripts/utils.js

* Parallel load stack for Unity enabled page performance
Call stack with the changes
Resolves: [MWPW-163234](https://jira.corp.adobe.com/browse/MWPW-163234)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/products/photoshop/edit-photos
- After: https://unityload--cc--adobecom.hlx.live/products/photoshop/edit-photos

MWPW-163234 | Parallel load stack for Unity enabled page performance

---

creativecloud/blocks/unity/unity.js
creativecloud/scripts/utils.js

Reverts adobecom/cc#480
Test URLs:
Before: https://main--cc--adobecom.hlx.live/products/photoshop/edit-photos
After: https://revert-480-unityload--cc--adobecom.hlx.live/products/photoshop/edit-photos

Revert "MWPW-163234 | Parallel load stack for Unity enabled page performance"

---

creativecloud/features/cc-forms/forms/trials.js

region and timezone

---

creativecloud/blocks/unity/unity.js
creativecloud/scripts/utils.js

- https://github.com/adobecom/cc/pull/493
**Creative cloud:**
- After: https://stage--cc--adobecom.hlx.live/?martech=off

[Release] Stage to Main 12/11

---

creativecloud/blocks/cc-forms/cc-forms.js

adding enterprise

---

creativecloud/features/cc-forms/components/checkbox.js

Lint issue fix

---

creativecloud/features/cc-forms/components/textfield.js

email pattern

---

creativecloud/blocks/cc-forms/cc-forms.css
creativecloud/features/cc-forms/components/checkbox.js
creativecloud/features/cc-forms/components/textfield.js
creativecloud/features/cc-forms/forms/trials.js

checkbox checks

---

creativecloud/features/cc-forms/forms/perpeptual.js
creativecloud/features/cc-forms/forms/trials.js

Remove loader on redirect

---

creativecloud/features/cc-forms/forms/perpeptual.js
creativecloud/features/cc-forms/forms/trials.js

Remove loader

---

.github/workflows/servicenow.py
.github/workflows/servicenow.yaml

* Automate CMR creation in service now
Resolves: [MWPW-160311](https://jira.corp.adobe.com/browse/MWPW-160311)
**Test URLs:**
- After: https://cmr--cc--adobecom.hlx.live/?martech=off

MWPW-160311-automate CMR creation in service now

---

creativecloud/features/cc-forms/components/textfield.js

checkbox and pattern

---

creativecloud/features/cc-forms/components/textfield.js

phonenumber pattern

---

creativecloud/features/cc-forms/forms/demandbase.js

Resolves: [MWPW-165765](https://jira.corp.adobe.com/browse/MWPW-165765)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/drafts/suhjain/forms/connect?martech=off
- After: https://demandbase-fix-2--cc--adobecom.hlx.live/drafts/suhjain/forms/connect?martech=off

MWPW-165765 - [Forms] Demand base console error is seen when the tabbing is done on the page - Fix

---

creativecloud/scripts/utils.js

* Adds graybox to stageDomainMap
Resolves: [MWPW-163774](https://jira.corp.adobe.com/browse/MWPW-163774)
**Test URLs:**
- After: https://mwpw-163774--cc--sivasadobe.hlx.live//?martech=off

MWPW-163774: [Graybox-www] make links environment-aware (cc origin)

---

creativecloud/features/cc-forms/components/textfield.js

pattern changes

---

creativecloud/features/cc-forms/components/checkbox.js
creativecloud/features/cc-forms/components/dropdown.js
creativecloud/features/cc-forms/forms/connect.js
creativecloud/features/cc-forms/forms/demandbase.js
creativecloud/features/cc-forms/forms/trials.js

Dalp forms lint issue fix

---

creativecloud/blocks/cc-forms/cc-forms.js

CodeQl fix

---

creativecloud/features/cc-forms/forms/demandbase.js

Resolves: [MWPW-163194](https://jira.corp.adobe.com/browse/MWPW-163194)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/drafts/mathuria/dalpforms/perpeptual?martech=off
- After: https://demandbase-fix-2--cc--adobecom.hlx.live/drafts/mathuria/dalpforms/perpeptual?martech=off

[Forms] [Demandbase fix] Hide popver when clicked outside

---

creativecloud/features/cc-forms/components/textfield.js

text field empty

---

creativecloud/blocks/interactive-metadata/interactive-metadata.js

* Choose the correct video to be displayed after selection on selector tray as the functionality got broken with the video block change in milo.
Resolves: [MWPW-165770](https://jira.corp.adobe.com/browse/MWPW-165770)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/products/photoshop/explore?martech=off
- After: https://mwpw-165770--cc--adobecom.hlx.live/products/photoshop/explore?martech=off

MWPW-165770 | Choose the correct video to be displayed after selection on selector tray

---

creativecloud/blocks/cc-forms/cc-forms.js
creativecloud/features/cc-forms/forms/perpeptual.js
creativecloud/features/cc-forms/forms/trials.js

consent load fix

---

creativecloud/features/cc-forms/components/checkbox.js
creativecloud/features/cc-forms/components/dropdown.js
creativecloud/features/cc-forms/components/textfield.js

validation error

---

creativecloud/features/cc-forms/components/checkbox.js
creativecloud/features/cc-forms/components/dropdown.js

validation on safari

---

creativecloud/features/cc-forms/components/dropdown.js

error message on iphone

---

creativecloud/features/cc-forms/components/checkbox.js
creativecloud/features/cc-forms/components/dropdown.js
creativecloud/features/cc-forms/components/textfield.js

error messages on ccqa

---

creativecloud/blocks/cc-forms/cc-forms.css

Resolves: [MWPW-166069](https://jira.corp.adobe.com/browse/MWPW-166069)
**Test URLs:**
- After: https://dalpForms--cc--adobecom.hlx.live/?martech=off

[cc forms] checkbox alignment fix

---

creativecloud/features/cc-forms/components/checkbox.js
creativecloud/features/cc-forms/components/dropdown.js
creativecloud/features/cc-forms/components/textfield.js

error messages

---

creativecloud/features/cc-forms/components/checkbox.js
creativecloud/features/cc-forms/components/dropdown.js

iphone error

---

creativecloud/features/cc-forms/components/checkbox.js
creativecloud/features/cc-forms/components/dropdown.js

scroll into view

---

creativecloud/blocks/cc-forms/cc-forms.js
creativecloud/features/cc-forms/components/dropdown.js
creativecloud/features/cc-forms/forms/trials.js
test/blocks/cc-forms/cc-forms.test.js
test/blocks/cc-forms/mocks/body.html
test/features/cc-forms/components/dropdown.test.js
test/features/cc-forms/forms/demandbase.test.js
test/features/cc-forms/forms/perpeptual.test.js
test/features/cc-forms/forms/trials.test.js

Mwpw 165982

---

test/blocks/cc-forms/cc-forms.test.js
test/blocks/cc-forms/mocks/body.html
test/features/cc-forms/forms/mocks/perpeptual-body.html
test/features/cc-forms/forms/perpeptual.test.js

* Adding more unit tests for perpeptual coverage
Resolves: [MWPW-165982](https://jira.corp.adobe.com/browse/MWPW-165982)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/drafts/mathuria/dalpforms/perpeptual?martech=off&georouting=off
- After: https://forms-unittest--cc--adobecom.hlx.live/drafts/mathuria/dalpforms/perpeptual1?martech=off&georouting=off

MWPW-165982 | Adding more unit tests for perpeptual coverage

---

creativecloud/blocks/cc-forms/cc-forms.js
creativecloud/features/cc-forms/forms/demandbase.js

* Refactored the `prepopulateFields()` function in Demandbase so that it selects and not appends a value to the select fields. 
* Added specific handling for country and state fields.
Resolves: [MWPW-166856](https://jira.corp.adobe.com/browse/MWPW-166856)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/drafts/drashti/dalpforms/perpeptual?martech=off
- After: https://db-fix--cc--adobecom.hlx.live/drafts/drashti/dalpforms/perpeptual?martech=off

[MWPW-166856] [Forms-demandbase] Prepopulate select fields correctly

---

creativecloud/blocks/unity/unity.js
creativecloud/scripts/utils.js

* Fetch libs from respective domains.
Resolves: [MWPW-167586](https://jira.corp.adobe.com/browse/MWPW-167586)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/drafts/sharathkannan/document?martech=off
- After: https://mwpw-167586--cc--sharath-kannan.hlx.live/drafts/sharathkannan/document?martech=off

Fix(MWPW-167586): Helix upgrade fix.

---

creativecloud/features/cc-forms/forms/demandbase.js

* Demandbase mobile issue fix
Resolves: [MWPW-167281](https://jira.corp.adobe.com/browse/MWPW-167281)
**Test URLs:**
- Before: https://main--cc--adobecom.aem.live/drafts/mathuria/dalpforms/perpeptual?martech=off
- After: https://db-mobile--cc--adobecom.aem.live/drafts/mathuria/dalpforms/perpeptual?martech=off

[MWPW-167281] 'state' field is empty and unclickable when we change the org name in the form for mobile

---

creativecloud/blocks/unity/unity.js
creativecloud/scripts/utils.js

Reverts adobecom/cc#613
Test URLs:
Before: https://main--cc--adobecom.hlx.live/drafts/sharathkannan/document?martech=off
After: https://revert-613-MWPW-167586--cc--sharath-kannan.hlx.live/drafts/sharathkannan/document?martech=off

Revert "Fix(MWPW-167586): Helix upgrade fix."

---

.github/preview-index/README.md
.github/preview-index/src/indexFull.js
.github/preview-index/src/sharepoint.js
.github/pull_request_template.md
.github/workflows/merge-to-stage.js
creativecloud/blocks/unity/unity.js
creativecloud/features/changeBg/changeBg.js
creativecloud/scripts/utils.js
libs/deps/README
test/blocks/interactive-metadata/mocks/interactive-metadata.html
test/features/firefly/mocks/body.html
test/features/firefly/mocks/masonry-body.html
tools/sidekick/config.json
web-test-runner.config.mjs

Reverts adobecom/cc#484
Before: https://main--cc--adobecom.hlx.live/products/photoshop?martech=off
After: https://revert-484-hlx-5--cc--adobecom.hlx.live/?martech=off
After-2: https://hlx-5--cc--adobecom.aem.live/products/photoshop?martech=off

Revert "Support both .aem. and .hlx. - HLX5 Support"

---

creativecloud/blocks/unity/unity.js
creativecloud/scripts/utils.js

* Fetch libs from respective domains.
Resolves: [MWPW-167586](https://jira.corp.adobe.com/browse/MWPW-167586)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/drafts/sharathkannan/document?martech=off
- After: https://revert-619-revert-613-MWPW-167586--cc--sharath-kannan.hlx.live/drafts/sharathkannan/document?martech=off

MWPW-167586 | Helix upgrade fix

---

creativecloud/features/cc-forms/components/textfield.js

iphone validation

---

creativecloud/features/cc-forms/forms/trials.js

* Correct error page for forms error
Resolves: [MWPW-168029](https://jira.corp.adobe.com/browse/MWPW-168029)
**Test URLs:**
- After: https://errorpagefix--cc--adobecom.aem.live/?martech=off

MWPW-168029 | Correct error page for forms error

---

creativecloud/blocks/cc-forms/cc-forms.css

Resolves: [MWPW-166069](https://jira.corp.adobe.com/browse/MWPW-166069)
**Test URLs:**
- After: https://checkbox--cc--adobecom.aem.live/?martech=off

[MWPW-166069] fix checkbox alignment in cc forms

---

creativecloud/blocks/cc-forms/cc-forms.css

Reverts adobecom/cc#627
Test URLs:
Before: https://main--cc--adobecom.aem.live/?martech=off
After: https://.revert-627-checkbox--cc--adobecom.aem.live/?martech=off

Revert "[MWPW-166069] fix checkbox alignment in cc forms"

---

tools/sidekick/config.json

* Update sidekick config json for hlx5
Resolves: [MWPW-168482](https://jira.corp.adobe.com/browse/MWPW-168482)
**Test URLs:**
- After: https://hlx5cfg--cc--adobecom.aem.live/?martech=off

MWPW-168482 | Update sidekick config json for hlx5

---

creativecloud/blocks/interactive-metadata/interactive-metadata.css

* Replaced unsupported css property.
Resolves: [MWPW-168392](https://jira.corp.adobe.com/browse/MWPW-168392)
**Test URLs:**
- Before: https://main--cc--adobecom.aem.live/drafts/sharathkannan/accessiblity/startover?martech=off
- After: https://mwpw-168392--cc--sharath-kannan.aem.live/drafts/sharathkannan/accessiblity/startover?martech=off

MWPW-168392 | Interactive marquee CTA alignment.

---

creativecloud/blocks/unity/unity.js

Reverts adobecom/cc#586
Before: https://main--cc--adobecom.aem.live/
After: https://revert-586-unityv2migration--cc--adobecom.aem.live/unityversion=v2&unitylibs=psv2migration&martech=off&georouting=off

Revert "MWPW-157950 | Migrating CC to unity V2 for performance and flexibility"

---

creativecloud/scripts/utils.js

* Exclude genuine urls from transforming based on environment
Resolves: [MWPW-168445](https://jira.corp.adobe.com/browse/MWPW-168445)
**Test URLs:**
- Before: https://stage--cc--adobecom.hlx.live/drafts/ruchika/mwpw-168445?martech=off
- After: https://mwpw-168445--cc--adobecom.hlx.live/drafts/ruchika/mwpw-168445?martech=off

MWPW-168445- Exclude genuine urls from transforming based on environment

---

.github/workflows/servicenow.py
.github/workflows/servicenow.yaml

* Automate CMR creation in service now
Resolves: [MWPW-160311](https://jira.corp.adobe.com/browse/MWPW-160311)
**Test URLs:**
- After: https://cmr-fix--cc--adobecom.hlx.live/?martech=off

MWPW-160311-Fix CMR automation

---

creativecloud/blocks/sidenav/sidenav.css

Reverts adobecom/cc#650
**Test URLs:**
- After: https://revert-650-MWPW-166688--cc--adobecom.aem.live/?martech=off

Revert "MWPW-166688: [Milo Plans Page] Category Filters for Plans page - contrast adjustments"

---

creativecloud/features/cc-forms/components/dropdown.js

Localized odin urls for dropdowns
Resolves: [MWPW-167457](https://jira.corp.adobe.com/browse/MWPW-167457)
**Test URLs:**
- Before: https://main--cc--adobecom.aem.live/drafts/mathuria/dalpforms/connect1?martech=off
- After: https://MWPW-167457--cc--adobecom.aem.live/drafts/mathuria/dalpforms/connect1?martech=off

MWPW-167457 | Localized odin urls for dropdowns

---

creativecloud/blocks/cc-forms/cc-forms.js
creativecloud/features/cc-forms/forms/subscribe.js

[Testing] Subscribe variant forms - PR to CCQA

---

creativecloud/blocks/cc-forms/cc-forms.css
creativecloud/blocks/cc-forms/cc-forms.js
creativecloud/features/cc-forms/components/checkbox.js
creativecloud/features/cc-forms/forms/trials.js
creativecloud/features/cc-forms/forms/unsubscribe.js

unsubscribe form

---

creativecloud/features/cc-forms/forms/unsubscribe.js

click of button

---

creativecloud/features/cc-forms/forms/trials.js

Unsubscribe

---

test/features/cc-forms/forms/mocks/unsubscribe-body.html
test/features/cc-forms/forms/unsubscribe.test.js

test cases

---

tools/trustcenter/js/utils.js

Encrypt tool

---

creativecloud/blocks/trustcenter-metadata/trustcenter-metadata.css
creativecloud/blocks/trustcenter-metadata/trustcenter-metadata.js

Mwpw 165831

---

creativecloud/blocks/trustcenter-metadata/trustcenter-metadata.css
creativecloud/blocks/trustcenter-metadata/trustcenter-metadata.js
tools/trustcenter/protecturl.html

Spacing fix

---

creativecloud/blocks/sidenav/sidenav.js
test/blocks/sidenav/sidenav.test.html.js

Resolves: [MWPW-170137](https://jira.corp.adobe.com/browse/MWPW-170137)
This will fix the issue number 1.
**Creative cloud:**
- After: https://MWPW-170137--cc--adobecom.aem.live/?martech=off
*This is related to this PR: https://github.com/adobecom/milo/pull/4001

MWPW-170137: Fixing the sidenav link decoration.

---

creativecloud/blocks/trustcenter-metadata/trustcenter-metadata.js

Trustcenter changes

---

creativecloud/blocks/trustcenter-metadata/trustcenter-metadata.css

Fix flicker

---

creativecloud/blocks/trustcenter-metadata/trustcenter-metadata.js

base64 url safe

---

creativecloud/blocks/trustcenter-metadata/trustcenter-metadata.js

hide download when loader is visible

---

creativecloud/blocks/image-prompt/image-prompt.js
creativecloud/blocks/unity/unity.js
creativecloud/features/cc-forms/forms/demandbase.js
creativecloud/features/cc-forms/forms/trials.js

- Fixed Cross-site scripting vulnerabilities. 
- Fixed DOM Based Cross-Site Scripting attack (DOMXSS). 
- Fixed Server-Side Request Forgery (Ssrf). 
- Fixed Open Redirect vulnerability (OR).
Resolves:
Cross-site Scripting (XSS) vulnerability: [MWPW-165424](https://jira.corp.adobe.com/browse/MWPW-165424), [MWPW-165425](https://jira.corp.adobe.com/browse/MWPW-165425)
DOM Based Cross-Site Scripting attack (DOMXSS) vulnerability: [MWPW-167298](https://jira.corp.adobe.com/browse/MWPW-167298)
Server-Side Request Forgery (Ssrf) vulnerability: [MWPW-164079](https://jira.corp.adobe.com/browse/MWPW-164079)
Open Redirect (OR) vulnerability: [MWPW-167834](https://jira.corp.adobe.com/browse/MWPW-167834) , [MWPW-167835](https://jira.corp.adobe.com/browse/MWPW-167835) , …

Kodiak Fixes: Fixed Cross-site scripting vulnerabilities

---

.github/workflows/merge-to-stage.js
creativecloud/blocks/cc-forms/cc-forms.js
creativecloud/blocks/interactive-metadata/interactive-metadata.js
creativecloud/blocks/nonprofit/nonprofit.css
creativecloud/blocks/nonprofit/nonprofit.js
creativecloud/blocks/upload/upload.css
creativecloud/blocks/upload/upload.js

MWPW-168411 DALP Form migration | Unsubscribe variant
Resolves: [MWPW-168411(https://jira.corp.adobe.com/browse/MWPW-168411)](https://jira.corp.adobe.com/browse/MWPW-NUMBER)
**Test URLs:**
- Before: https://main--cc--adobecom.aem.page/drafts/suhjain/forms/unsubscribe
- After: https://unsubscribe--cc--adobecom.aem.live/
Testing links:
/drafts/suhjain/forms/unsubscribe?p=QvTylbSZMKjEOgdnTDj%2FcXFRp4rfULx3c6nlD%2FTp7H3ZC4uziIcucjD1%2BnuhMBff0rbACuff37ei5QOKm8in1vfqh1Y%2F4FLjYRD1D0Gl3iZ2R5yQy1VDh35gb9HZunoVZpGDjm3Kk0QN6O%2BqqpmRA6RC4n7Yj%2BSUE%2BetlXJWgWBCQ%2BatWSWMgLmrwnJZnrwMWQ%3D%3D&src=aci&type=macrupdates&n=sV0eIhWBHdVZH5qvsTHAkw%3D%3D&email=d*************5%40a*******t.com&legacy=false#

MWPW-168411 DALP Form migration | Unsubscribe variant

---

creativecloud/features/interactive-components/generate/generate.js
creativecloud/features/interactive-components/start-over/start-over.js

- Fixed Interactive Marquee - Purpose of link is not clear in context
Resolves: [MWPW-172494](https://jira.corp.adobe.com/browse/MWPW-172494)
**Test URLs:**
- After: https://mwpw-172494-interactive-marquee--cc--adobecom.aem.live/?martech=off

MWPW-172494: Fixed Interactive Marquee - Purpose of link is not clear in context

---

creativecloud/scripts/utils.js

* Eager load image in CC Configurable widget (Upload Block)
Resolves: [MWPW-174767](https://jira.corp.adobe.com/browse/MWPW-174767)
**Test URLs:**
- Before: https://stage--cc--adobecom.aem.live/products/photoshop/how-to-use?unitylibs=main&martech=off
- After: https://unity-performance--cc--adobecom.aem.live/products/photoshop/how-to-use?unitylibs=main&martech=off

[MWPW-174767] Eager load image in CC Configurable widget (Upload Block)

---

helix-query.yaml

- Sitemaps added for solutions pages.
Resolves: [MWPW-175464](https://jira.corp.adobe.com/browse/MWPW-175464), [MWPW-175465](https://jira.corp.adobe.com/browse/MWPW-175465), [MWPW-175466](https://jira.corp.adobe.com/browse/MWPW-175466)
**Test URLs:**
- After: https://mwpw-175464-sitemap-dalp-us--cc--adobecom.aem.live/?martech=off

Fix(MWPW-175464): Sitemap for DALP US & ROW

---

.github/workflows/merge-to-stage.js

* Workflow enhanced.
Resolves: [MWPW-173330](https://jira.corp.adobe.com/browse/MWPW-173330)
**Test URLs:**
- Before: https://main--cc--adobecom.aem.live/drafts/sharathkannan/accessiblity/document?martech=off
- After: https://workflow-test--ccsh--sharath-kannan.aem.live/drafts/sharathkannan/accessiblity/document?martech=off

Fix(MWPW-173330): Workflow Merges PRs with changes to same file in a single batch.

---

creativecloud/blocks/interactive-metadata/interactive-metadata.css

- https://github.com/adobecom/cc/pull/779
**Creative cloud:**
- After: https://stage--cc--adobecom.aem.live/?martech=off

[Release] Stage to Main 09/29
