adobecom/cc

- tools/sidekick/config.json
This PR enables locales tool feature in sidekick. It also updates the url for send to caas and library (as in milo).
Test URLs:
NA
> Enable the new locales tool feature in sidekick

- cc/styles/styles.css
Adding top and bottom padding to reading-width
Resolves: [MWPW-127801](https://jira.corp.adobe.com/browse/MWPW-127801)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/creativecloud/design/hub/guides/add-elegance-or-vintage-flair-with-dusty-rose?martech=off
- After: https://main--cc--aishwaryamathuria.hlx.page/creativecloud/design/hub/guides/add-elegance-or-vintage-flair-with-dusty-rose?martech=off
> MWPW-127801 Adding top and bottom padding to reading-width

- creativecloud/scripts/scripts.js
* Content root is required by georouting and placeholders. Since we are not adding content in root and we have redirection added from creativecloud folder this would be required to make sure it loads these jsons from correct folder.
Resolves: [MWPW-127801](https://jira.corp.adobe.com/browse/MWPW-127801)
**Test URLs:**
- Before: https://www.stage.adobe.com/creativecloud/design/hub/guides/add-elegance-or-vintage-flair-with-dusty-rose.html?martech=off
- After: https://contentroot--cc--aishwaryamathuria.hlx.page/creativecloud/design/hub/guides/add-elegance-or-vintage-flair-with-dusty-rose?martech=off
> Re adding contentRoot. 

- helix-sitemap.yaml
* x-default is missing form sitemap. Adding info for same.
Resolves: [MWPW-128672](https://jira.corp.adobe.com/browse/MWPW-128672)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/de/creativecloud/sitemap.xml
- After: https://main--cc--aishwaryamathuria.hlx.page/de/creativecloud/sitemap.xml
> MWPW-128672 Update helix-sitemap yaml to have x-default

- helix-sitemap.yaml
* Creating this PR to test if this fixes the duplicate data coming in sitemap.xml in certain scenarios (when we have 2 entries in helix-sitemap.yaml for same source and destination but different hreflang). This PR will be reverted if it doesn't fix the issue. 
**Test URLs:**
-Before: https://main--cc--adobecom.hlx.page/de/creativecloud/sitemap.xml
-After: https://helix-query-fix--cc--adobecom.hlx.page/de/creativecloud/sitemap.xml
> Helix query fix

- helix-sitemap.yaml
* Trying another fix for duplicate data in us sitemap. 
Resolves: [MWPW-130603](https://jira.corp.adobe.com/browse/MWPW-130603)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/de/creativecloud/sitemap.xml
- After: https://helix-query-fix--cc--adobecom.hlx.page/de/creativecloud/sitemap.xml
> Take2: Fix for duplicate data in us sitemap

- helix-sitemap.yaml
* Helix query fix: adding hreflang for default for x-default key
Resolves: [MWPW-128672](https://jira.corp.adobe.com/browse/MWPW-128672)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/creativecloud/sitemap.xml
- After: https://main--cc--aishwaryamathuria.hlx.page/creativecloud/sitemap.xml
> Helix query fix: adding hreflang for default for x-default key

- 404.html
* Removing feds header form 404 as when milo central 404 change is merged in milo main branch it will break cc production 404 and will give following page https://main--cc--adobecom.hlx.live/this-doesnt-exist?milolibs=central-404
*Once all new 404 pages are authored we will add the meta tag in main
Resolves: [MWPW-130971](https://jira.corp.adobe.com/browse/MWPW-130971)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/this-doesnt-exist?milolibs=central-404
- After: https://404fedsheader--cc--adobecom.hlx.live/this-doesnt-exist?milolibs=central-404
> Removing feds header from 404

- creativecloud/scripts/scripts.js
* Add pdf embed api support for CC pages to view the pdf on page
Resolves: [MWPW-130346](https://jira.corp.adobe.com/browse/MWPW-130346)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/drafts/dstrong/cors-test?martech=off
- After: https://pdf-embed-api--cc--adobecom.hlx.page/drafts/dstrong/cors-test?martech=off
Note: Credential for live in PR are for main branch. Hence to open pdf in feature branch we'll need to update the credential for feature branch in git.
> Support pdf viewer in CC

- helix-query.yaml
* Update helix query to add substance3D pages to sitemap
Resolves: [MWPW-131783](https://jira.corp.adobe.com/browse/MWPW-131783)
**Test URLs:**
NA
> add substance3D pages to the sitemap(US only)

- tools/sidekick/config.json
* Add tag selector plugin to the sidekick
Resolves: [MWPW-134018](https://jira.corp.adobe.com/browse/MWPW-134018)
**Test URLs:**
- After: https://tagSelector--cc--adobecom.hlx.page/?martech=off
> Add tag selector plugin to sidekick

- tools/sidekick/config.json
* fix bottom cut off issue of tag selector plugin
Resolves: [MWPW-134018](https://jira.corp.adobe.com/browse/MWPW-134018)
**Test URLs:**
- After: https://tag-selector--cc--adobecom.hlx.page/?martech=off
Note: Open the above pages in edit mode to see tag selector in plugin and see the change
> update top value for tag selector plugin

- tools/sidekick/config.json
Reverts adobecom/cc#67
as jira ticket https://jira.corp.adobe.com/browse/MWPW-132559 is closed now and send to caas option in sidekick can be re-enabled
> Revert "disable send to caas in config"

- helix-query.yaml
- add separate index defintion for merch cards
- needed as data source for card collections
Resolves: [MWPW-135538](https://jira.corp.adobe.com/browse/MWPW-135538)
**Test URLs:**
- After: https://mwpw-135538--cc--honstar.hlx.page/?martech=off
> MWPW-135538 - Define query-index for cards

- tools/sidekick/config.json
* Add links to CaaS and FaaS configurator to the sidekick
* Link to these configurators has been added under Tools
* Configurator page will open in a new tab in browser
Resolves: [MWPW-134192](https://jira.corp.adobe.com/browse/MWPW-134192)
**Test URLs:**
- After: https://sidekick--cc--ruchika4.hlx.page/?martech=off
> MWPW-134192-Add caas and faas configurator to sidekick

- helix-query.yaml
Resolves: [MWPW-137735](https://jira.corp.adobe.com/browse/MWPW-137735)
As more and more pages located under `/products` have to go live and be a part of EDS sitemap, we decided to update index definition to include everything located under /products directory.
The same behavior is already adopted for `/creativecloud`, so it's not something new for GWP.
With this PR, all in-progress pages were moved out of `/products`. In-progress pages, that couldn't be moved out, were marked as 'no-index, no-follow', so that they don't appear in the sitemap until go live. This was done in global metadata.
Starting from now, for any newly added to `/products` page, that should not be in sitemap, 'no index, no-follow' is required.
**Test URLs:**
No before/after URLs required, since it's an index update.
> MWPW-137735: update sitemap index

- creativecloud/features/interactive-elements/interactive-elements.css
- creativecloud/features/interactive-elements/interactive-elements.js
* Remove important from css
Resolves: [MWPW-138426](https://jira.corp.adobe.com/browse/MWPW-138426)
**Test URLs:**
- Before: https://stage--cc--adobecom.hlx.live/drafts/ruchika/firefly/firefly-latest?martech=off
- After: https://stage-ff--cc--adobecom.hlx.live/drafts/ruchika/firefly/firefly-latest?martech=off
> [Stage]MWPW-138426-Remove important from css

- creativecloud/features/interactive-elements/interactive-elements.css
* Enticement css fix
Resolves: [MWPW-140087](https://jira.corp.adobe.com/browse/MWPW-140087)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/drafts/ruchika/firefly/firefly-latest?martech=off
- After: https://enticement--cc--adobecom.hlx.live/drafts/ruchika/firefly/firefly-latest?martech=off
Note: This fix was applied in the genfill css file. Moving it to interactive-elements.css so that it is applied to enticement used for all blocks
> MWPW-140087-fix enticement css

- creativecloud/blocks/interactive-marquee/interactive-marquee.js
- creativecloud/features/genfill/genfill-interactive.css
- creativecloud/features/genfill/genfill-interactive.js
- test/features/genfill/genfill-interactive.test.js
- test/features/genfill/mocks/genfill.html
* Bug fix - Image flickering issue on firefox browser (Genfill)
Resolves: [MWPW-140096](https://jira.corp.adobe.com/browse/MWPW-140096)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/drafts/drashti/MWPW-137345/genfill-container?martech=off
- After: https://genfill-flicker--cc--drashti1712.hlx.live/drafts/drashti/MWPW-137345/genfill-container?martech=off
> [MWPW-140096] Genfill Marquee images are blinking during auto play and on click as well in Firefox browser

- helix-query.yaml
* as per request from GWP, adjusting query-index path for merch-card documents
Resolves: [MWPW-140993](https://jira.corp.adobe.com/browse/MWPW-140993)
**Test URLs:**
- After: https://mwpw-140993--cc--honstar.hlx.live/?martech=off
> MWPW-140993 - [CC] update query-index path for merch-cards

- creativecloud/scripts/scripts.js
- creativecloud/scripts/utils.js
- implement `decorateArea` function from milo (see adobecom/milo#1623)
- only run `loadLCPImage` function if no previous LCP image has been set already
Resolves: [MWPW-139621](https://jira.corp.adobe.com/browse/MWPW-139621)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/products/special-offers?martech=off
- After: https://mwpw-139621--cc--honstar.hlx.live/products/special-offers?martech=off
> MWPW-139621 - LCP image loading of fragments

- creativecloud/scripts/scripts.js
* Add vn_vi and vn_en to the locales in config
Resolves: [MWPW-140715](https://jira.corp.adobe.com/browse/MWPW-140715)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/ae_en/creativecloud/tools/app-design-software#langnav
- After: https://new-geos--cc--adobecom.hlx.live/ae_en/creativecloud/tools/app-design-software#langnav
> MWPW-140715-Add new locales in config

- helix-query.yaml
- helix-sitemap.yaml
* Out of scope geos for batch 1C ROW
DK, ES, FI, IT, NL, NO, SE,  LA, MX,  BE_nl, BG,  CH_it, CZ, EE,  HU, IL_he, MENA_ar, PL, PT, RO, SI, SK,  TR, UA
* This PR removes the above geos except below as they were added as part of previous ROW release are needed for those batches
ES, IT, NL, PL, TR
Resolves: [MWPW-138378](https://jira.corp.adobe.com/browse/MWPW-138378)
**Test URLs:**
NA
> Remove out of scope geos from sitemap for batch 1C ROW

- creativecloud/blocks/interactive-marquee/interactive-marquee.js
- creativecloud/blocks/interactive-marquee/milo-marquee.css
* Resolved the discrepancies that listed in the jira for GenFill marquee (issue 2, 3 and 4)
* Changed the button to 50px height (button-xl)
* Modified the structure of the interactive marquee so that it matches Marquee medium.
* The icon text is set to 18px font size across all breakpoints
Resolves: [MWPW-140669](https://jira.corp.adobe.com/browse/MWPW-140669)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/drafts/drashti/MWPW-137345/genfill-container?martech=off
- After: https://genfill-fix--cc--drashti1712.hlx.live/drafts/drashti/MWPW-137345/genfill-container?martech=off
> [MWPW-140669][Milo - Interactive marquee] missed specs from Figma file #2, #3 and #4

- creativecloud/scripts/scripts.js
this is going to enable generation of localised Download urls towards these domains.
e.g: https://helpx.adobe.com/download-install.html
GWP will author this in US/EN only, and it will be automatically localized by Milo.
for locales who do not have this page published,  GWP has capability to override the URL.
related to: https://github.com/adobecom/milo/pull/1739
> MWPW-136892: update prod domains

- creativecloud/features/firefly/firefly-interactive.js
- creativecloud/features/firefly/firefly-susi.js
- creativecloud/scripts/scripts.js
* Fix to redirect user directly firefly product page from adobe.com page.
* We have updated allowed list for this in out client id too.
Resolves: [MWPW-140914](https://jira.corp.adobe.com/browse/MWPW-140914)
**Test URLs:**
- Before: https://stage--cc--adobecom.hlx.live/drafts/ruchika/firefly/remove-dnt/document1?martech=off
- After: https://firefly-login--cc--adobecom.hlx.live/drafts/ruchika/firefly/remove-dnt/document1?martech=off
> MWPW-140914-Redirect user directly to firefly product page from firefly marketing page

- .vscode/extensions.json
* Adding the extension in the list of recommended vscode extensions
* This extension can also be found in the vscode marketplace by the id virtual-comments
Resolves: [MWPW-140716](https://jira.corp.adobe.com/browse/MWPW-140716)
> [MWPW-140716] Integrating virtual comments extension with CC

- creativecloud/blocks/interactive-marquee/milo-marquee.css
- creativecloud/features/firefly/firefly-interactive.css
* Set padding for media in interactive marquee container to 0 so that padding set in media.css is not applied to it.
* Fix the font-size for product name and per figma
* Fix extra padding showing up only in firefly marquee in mobile and tablet which was added to interactive marquee css [here](https://github.com/adobecom/cc/pull/151/files)
Resolves: [MWPW-141962](https://jira.corp.adobe.com/browse/MWPW-141962)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/products/firefly?martech=off
- After: https://mwpw-141962--cc--adobecom.hlx.page/products/firefly?martech=off
> MWPW-141962-Fix interactive marquee css issues

- creativecloud/scripts/scripts.js
* Add go urls in html exclude list
Resolves: [MWPW-142788](https://jira.corp.adobe.com/browse/MWPW-142788)
**Test URLs:**
- After: https://gourl--cc--adobecom.hlx.page/?martech=off
Note: This is a blocker issue for today's ongoing release. We need to exclude milo from appending .html for any /go/** urls
> MWPW-142788-add go url to html exclude list

- creativecloud/scripts/scripts.js
* Add go urls in html exclude list
Resolves: [MWPW-142788](https://jira.corp.adobe.com/browse/MWPW-142788)
**Test URLs:**
- After: https://gourl--cc--adobecom.hlx.page/?martech=off
Note: This is a blocker issue for today's ongoing release. We need to exclude milo from appending .html for any /go/** urls
> [Main]MWPW-142788-add go url to html exclude list

- creativecloud/blocks/sidenav/sidenav.js
- test/blocks/sidenav/sidenav.test.html
- test/blocks/sidenav/sidenav.test.html.js
Resolves: [MWPW-143215](https://jira.corp.adobe.com/browse/MWPW-143215)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/drafts/gewittig/catalog-test?martech=off
- After: https://mwpw-143215--cc--npeltier.hlx.page/drafts/gewittig/catalog-test?martech=off
> MWPW-143215 [sidenav]  make re-ordering possible with camel case

- creativecloud/blocks/universal-promo-terms/universal-promo-terms.js
- test/blocks/universal-promo-terms/universal.promo.terms.test.js
Resolves: [MWPW-141444](https://jira.corp.adobe.com/browse/MWPW-141444)
Josh King wants this update
**Test URLs:**
- Before: https://stage--cc--adobecom.hlx.live/creativecloud/offers/promo-terms?offer_id=1B365A793986BBEEE26F3E372BDAAB09&country=DE&locale=de_DE&promotion_code=fixed_dis_20&martech=off
- After: https://universal-promo-terms--cc--adobecom.hlx.live/creativecloud/offers/promo-terms?offer_id=1B365A793986BBEEE26F3E372BDAAB09&country=DE&locale=de_DE&promotion_code=fixed_dis_20&martech=off
> service_providers is now optional as api_key

- creativecloud/features/firefly/firefly-interactive.css
- creativecloud/features/firefly/firefly-interactive.js
* Handle css for 2 values in selector tray
Resolves: [MWPW-143533](https://jira.corp.adobe.com/browse/MWPW-143533)
**Test URLs:**
2 options in selector tray:
- Before: https://main--cc--adobecom.hlx.live/drafts/ruchika/firefly/remove-dnt/document2?martech=off
- After: https://selector-tray--cc--adobecom.hlx.live/drafts/ruchika/firefly/remove-dnt/document2?martech=off
3 options in selector tray:
- After: https://selector-tray--cc--adobecom.hlx.live/drafts/ruchika/firefly/remove-dnt/document1?martech=off
No change in UI for 3 options in selector tray
> MWPW-143533-Handle css for 2 values in selector tray

- creativecloud/scripts/scripts.js
* ClientId updated for stage.adobe.com
Resolves: [MWPW-143472](https://jira.corp.adobe.com/browse/MWPW-143472)
**Test URLs:**
- Before: https://www.stage.adobe.com/creativecloud/business/teams/resources/sdk/computer-sas-industry-insights.html?martech=off
- After: https://mwpw-143472--cc--sharath-kannan.hlx.page/?martech=off
The test url given above is just a placeholder as the clientid is picked based on the domain,I have tested the clientID at runtime in the browser.
> clientId for pdfviewer updated

- creativecloud/blocks/sidenav/sidenav.js
- test/blocks/sidenav/sidenav.test.html
- test/blocks/sidenav/sidenav.test.html.js
when parents are auto-generated, they don't work well (no value => no unfold, no filtering)
Resolves: [MWPW-143426](https://jira.corp.adobe.com/browse/MWPW-143426)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/drafts/npeltier/catalog?martech=off
- After: https://mwpw-143426--cc--npeltier.hlx.page/drafts/npeltier/catalog?martech=off
> MWPW-143426 fixing sidenav parents when implicitly declared

- .github/workflows/log-previews.yml
Add git action for testing bulk preview logs in default branch. 
This is only for stage and will be reverted.
Resolves: [MWPW-144005](https://jira.corp.adobe.com/browse/MWPW-144005)
**Test URLs:**
- After: https://test-preview--cc--adobecom.hlx.page/?martech=off
> MWPW-144005 For testing handle preview events from helix admin api

- creativecloud/sitemap-index.xml
- helix-query.yaml
- helix-sitemap.yaml
* Remove mt and cy_en from CC sitemap
Resolves: [MWPW-143057](https://jira.corp.adobe.com/browse/MWPW-143057)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/creativecloud/sitemap-index.xml
- After: https://sitemap-update--cc--adobecom.hlx.page/creativecloud/sitemap-index.xml
> MWPW-143057-Remove mt and cy_en from CC sitemap

- codecov.yaml
- package.json
- web-test-runner.config.mjs
Fixing the code coverage plugin path
Stage PR: https://github.com/adobecom/cc/pull/229
Resolves: [MWPW-144525](https://jira.corp.adobe.com/browse/MWPW-144525)
Test URLs:
Before: https://main--cc--adobecom.hlx.live/?martech=off
After: https://codecov--cc--aishwaryamathuria.hlx.live/?martech=off
> MWPW-144525 | Fixing the code coverage plugin path

- .kodiak/config.yaml
- creativecloud/blocks/interactive-marquee/interactive-marquee.js
- creativecloud/blocks/interactive-marquee/milo-marquee.css
- creativecloud/features/firefly/firefly-interactive.css
- creativecloud/features/firefly/firefly-interactive.js
- creativecloud/features/genfill/genfill-interactive.css
- creativecloud/features/genfill/genfill-interactive.js
- creativecloud/features/interactive-elements/interactive-elements.css
- creativecloud/features/interactive-elements/interactive-elements.js
Syncing following PRs from stage to Main
- https://github.com/adobecom/cc/pull/219
- https://github.com/adobecom/cc/pull/244
- https://github.com/adobecom/cc/pull/250
- https://github.com/adobecom/cc/pull/255
Test URLs:
Before - https://main--cc--adobecom.hlx.live
After - https://stage--cc--adobecom.hlx.live
> [Release] Sync main from stage 1/4/2024

- tools/sidekick/config.json
Syncing following PR from stage to Main
- https://github.com/adobecom/cc/pull/258
- https://github.com/adobecom/cc/pull/260
**Test URLs:**
- After: https://stage--cc--adobecom.hlx.live/?martech=off
> [Release] Sync main from stage 2/4/2024

- .hlxignore
- remove root json,
- remove code coverage,
- generic rule for sidekick like nested json
**Test URLs:**
- After:  https://hlxignore--cc--npeltier.hlx.page/?martech=off
> @releng better hlxignore

- creativecloud/features/genfill/genfill-interactive.css
* Fixed the enticement position in genfill interactive marquees for RTL locale in page and fragment.
Resolves: [MWPW-145840](https://jira.corp.adobe.com/browse/MWPW-145840)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/drafts/drashti/bugs/genfill/document
- After: https://genfill-stage--cc--adobecom.hlx.live/drafts/drashti/bugs/genfill/document
> [MWPW-145840] Enticement position is not proper for RTL locale in page and fragment -- fixed

- creativecloud/scripts/scripts.js
Resolves: [DOTCOM-118347](https://jira.corp.adobe.com/browse/DOTCOM-118347)
If this becomes more nuanced like it's shown in [DOTCOM-112335](https://jira.corp.adobe.com/browse/DOTCOM-112335) you can try something like this util FEDS provides an official solution.
> DOTCOM-118347

- creativecloud/features/interactive-components/selector-tray/selector-tray.css
* Changing CSS for blue focus line to cover the whole div
Resolves: [MWPW-147501](https://jira.corp.adobe.com/browse/MWPW-147501)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/products/photoshop/explore/?martech=off
- After: https://mwpw-147501--cc--adobecom.hlx.live/products/photoshop/explore?martech=off
> MWPW-147501 | Changing CSS for blue focus line to cover the whole div

- creativecloud/blocks/interactive-marquee/milo-marquee.css
* Prevent CLS in interactive marquee when icon and text is configured side by side
Resolves: [MWPW-146794](https://jira.corp.adobe.com/browse/MWPW-146794) [MWPW-146757](https://jira.corp.adobe.com/browse/MWPW-146757)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/drafts/mathuria/interactiveelems/interactive-firefly?martech=off&georouting=off
- After: https://mwpw-146757--cc--adobecom.hlx.live/drafts/mathuria/interactiveelems/interactive-firefly?martech=off&georouting=off
> MWPW-146794 | Avoid CLS due to image

- creativecloud/blocks/interactive-marquee/interactive-marquee.js
- creativecloud/blocks/interactive-marquee/milo-marquee.css
- creativecloud/blocks/interactive-metadata/interactive-metadata.js
- creativecloud/blocks/sidenav/sidenav.js
- creativecloud/features/firefly/firefly-interactive.css
- creativecloud/features/firefly/firefly-susi.js
- creativecloud/features/interactive-components/selector-tray/selector-tray.css
- test/blocks/sidenav/mocks/blah.svg
- test/blocks/sidenav/sidenav.test.html
- test/blocks/sidenav/sidenav.test.html.js
- https://github.com/adobecom/cc/pull/254
- https://github.com/adobecom/cc/pull/276
- https://github.com/adobecom/cc/pull/281
- https://github.com/adobecom/cc/pull/283
- https://github.com/adobecom/cc/pull/284
- https://github.com/adobecom/cc/pull/285
**Test URLs:**
After: https://stage--cc--adobecom.hlx.live/careers?martech=off
> [Release] Sync main from stage 2/5/2024

- creativecloud/scripts/scripts.js
Continue to photoshop button is not seen working in stage ,proxy denied error is seen. Thus changed the dev env to stage.
Resolves: [MWPW-148165](https://jira.corp.adobe.com/browse/MWPW-NUMBER)
**Test URLs:**
- Before:https://main--cc--adobecom.hlx.page/drafts/suhjain/interactive-marquee/continuetops
- After: https://mwpw-148165--cc--adobecom.hlx.live/drafts/suhjain/interactive-marquee/continuetops
> MWPW-148165: continue to photoshop button is not seen working in stage ,proxy denied error is seen

- creativecloud/blocks/interactive-marquee/milo-marquee.css
- creativecloud/features/firefly/firefly-interactive.css
- creativecloud/features/genfill/genfill-interactive.css
- creativecloud/features/interactive-elements/interactive-elements.css
* Fixes the foreground container width of the interactive marquee so that the text does not touch the edge of the screen on lower desktop screen sizes
* Also fixes the generate prompt for firefly interactive marquee, which was going out of the image for screen size > 1200px and < 1300px.
Resolves: [MWPW-147521](https://jira.corp.adobe.com/browse/MWPW-147521)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/docs/library/kitchen-sink/interactive-marquee?martech=off
- After: https://int-fix--cc--drashti1712.hlx.live/drafts/drashti/bugs/interactive-marquee?martech=off
> [MWPW-147521] interactive marquee container is not seen displayed as expected with resize flow

- .github/workflows/merged-to-main.yaml
- .github/workflows/src/helpers.js
- .github/workflows/src/send-slack.js
* Added workflow to send **release notes** to Slack **cc-changelog** channel when **PR** is **merged** with **main** branch
* This workflow will be triggered once the PR is merged in main branch
Resolves: [MWPW-140115](https://jira.corp.adobe.com/browse/MWPW-140115)
Note: No impact on cc pages
**Test URLs:**
- After: https://mwpw-140115--cc--sivasadobe.hlx.live/?martech=off
> 140115 - Adding a workflow for sending release notes to the Slack change-log channel

- creativecloud/scripts/utils.js
* Eager load marquee background image only for current breakpoint
Resolves: [MWPW-153428](https://jira.corp.adobe.com/browse/MWPW-153428)
**Test URLs:**
- Before: https://stage--cc--adobecom.hlx.live/drafts/ruchika/eager-load?martech=off
- After: https://eagerload--cc--adobecom.hlx.live/drafts/ruchika/eager-load?martech=off
Test Page with 2 background images:
https://eagerload--cc--adobecom.hlx.live/drafts/ruchika/eager-load2?martech=off
Test Page with 1 background image:
https://eagerload--cc--adobecom.hlx.live/drafts/ruchika/eager-load1?martech=off
Test Page with no background image:
https://eagerload--cc--adobecom.hlx.live/drafts/ruchika/eager-load3?martech=off
> MWPW-153428-Eager load marquee background image only for current breakpoint

- creativecloud/scripts/mep/aexg4866/firefly/firefly-masonry.js
* Test Version of firefly-masonry block. Simple fix to increase charlimit on marquee prompt input via html attributes instead of manual javascript logic check before redirecting to AX web app on cta click. 
Resolves: [OPT-27991](https://jira.corp.adobe.com/browse/OPT-27991)
**Test URLs:**
- Before: https://stage--cc--adobecom.hlx.live/products/firefly/features/text-to-image?mep=%2Fcc-shared%2Ffragments%2Ftests%2F2024%2Fq3%2Faexg4866%2Faexg4866.json--target-var1-newmarquee&target=off
- After: https://aexg4866fixes--cc--adobecom.hlx.live/products/firefly/features/text-to-image?mep=%2Fcc-shared%2Ffragments%2Ftests%2F2024%2Fq3%2Faexg4866%2Faexg4866.json--target-var1-newmarquee&target=off
> OPT-27991 AEXG4866 - AX take over of FF T2i SEO page - FIXES

- creativecloud/scripts/mep/aexg4866/firefly/firefly-masonry.js
- creativecloud/scripts/mep/aexg4866/interactive-marquee/interactive-marquee.css
- creativecloud/scripts/mep/aexg4866/interactive-marquee/interactive-marquee.js
Merging the below PRs : 
* https://github.com/adobecom/cc/pull/353
* https://github.com/adobecom/cc/pull/354
Test URLs:
- Before: https://main--cc--adobecom.hlx.live/careers?martech=off
- After: https://stage--cc--adobecom.hlx.live/careers?martech=off
> [Release] Merge stage to main 7/18

- creativecloud/features/interactive-components/generate/generate.js
Adding an option to configure a generate button with prompt that is configurable based on the selected option in the selector tray.
/drafts/mathuria/interactiveelems/demo/handoff/totebag/brightorb
Resolves: [MWPW-147481](https://jira.corp.adobe.com/browse/MWPW-147481)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/drafts/mathuria/interactiveelems/demo/handoff/totebag/totebag-selector-update?martech=off
- After: https://mwpw-147481--cc--adobecom.hlx.live/drafts/mathuria/interactiveelems/demo/handoff/totebag/totebag-selector-update?martech=off
> MWPW-147481 | Enable configurable prompt for generate after select step

- creativecloud/scripts/utils.js
when there is only 1 image authored in tablet and in desktop we are able to see the eagerload is seen rendered for when the page is not in that viewport
Resolves: [[MWPW-154272]](https://jira.corp.adobe.com/browse/MWPW-NUMBER)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/drafts/Souj/html/marquee-variant61#
- After: https://loadsingleimg--cc--adobecom.hlx.live/drafts/Souj/html/marquee-variant61#
> [MWPW-154272]: Eager Loading only one image for each viewport

- creativecloud/deps/merch-sidenav.js
- creativecloud/scripts/utils.js
Disabled body scroll for merch-sidenav web component used in the catalog filter (on small screens it gets opened in a modal).
The AEM PSI check fails because the merch-card JS execution time is too long (around 1,057 ms), so the TBT score is too low.
The change in the PR is related only to merch-sidenav, which is not a culprit of low TBT, thus we can merge it, and should address the TBT score of the merch-card in a separate PR.
Corresponding tacocat PR: https://git.corp.adobe.com/wcms/tacocat.js/pull/613
Corresponding mas PR: https://github.com/adobecom/mas/pull/20
Resolves: [MWPW-147716](https://jira.corp.adobe.com/browse/MWPW-147716)
Test URLs:
Before: https://main--cc--adobecom.hlx.live/products/catalog?martech=off&georouting=off&mep=off
After: …
> MWPW-147716: Disabled background scroll for filter dialog

- creativecloud/deps/merch-sidenav.js
- creativecloud/features/interactive-components/generate/generate.js
- creativecloud/scripts/utils.js
Merging following PRs to main -
- https://github.com/adobecom/cc/pull/335
- https://github.com/adobecom/cc/pull/351
- https://github.com/adobecom/cc/pull/352
Test URLs:
After: https://stage--cc--adobecom.hlx.live/careers?martech=off
> [Release] Sync main from stage 7/22

- creativecloud/scripts/scripts.js
* This PR adds the `stageDomainsMap` to the config allowing links to be environment-aware.
More about this new feature can be found in [here](https://github.com/orgs/adobecom/discussions/2437).
* This PR is copy of https://github.com/adobecom/cc/pull/336 Test urls were not accessible on the previous hence a new PR has been opened.
Resolves: [MWPW-151457](https://jira.corp.adobe.com/browse/MWPW-151457)
**Test URLs:**
- Before: https://stage--cc--adobecom.hlx.live/drafts/rbogos/default?martech=off
- After: https://mwpw-151457--cc--adobecom.hlx.live/drafts/rbogos/default?martech=off
> [MWPW 151457] Added stage domains map to make links environment-aware

- .github/workflows/merge-to-stage.js
* The "ready for stage" label is mandatory before merging Pull requests into stage branch.
Resolves: [MWPW-154091](https://jira.corp.adobe.com/browse/MWPW-154091)
Test URLs:
Before: https://main--cc--adobecom.hlx.live/?martech=off
After: https://mwpw-154091--cc--sharath-kannan.hlx.live/?martech=off
> fix(MWPW-154091):ready for stage label is mandatory.

- creativecloud/features/interactive-components/selector-tray/selector-tray.css
* Changing the selector tray thumbnail size to be 98px x 98px as per the figma. 
* Reducing the border width to be 3px as per the figma
Resolves: [MWPW-153405](https://jira.corp.adobe.com/browse/MWPW-153405)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/products/photoshop/explore?martech=off&georouting=off&mep=off
- After: https://mwpw-153411--cc--adobecom.hlx.live/products/photoshop/explore?martech=off&georouting=off&mep=off
> MWPW-153405 | Changing the selector tray thumbnail size

- creativecloud/scripts/scripts.js
* Don't convert adobe.com urls to stage.adobe.com url
Resolves: [MWPW-155431](https://jira.corp.adobe.com/browse/MWPW-155431)
**Test URLs:**
- Before: https://stage--cc--adobecom.hlx.live/drafts/rbogos/default?martech=off
- After: https://stagedomain--cc--adobecom.hlx.live/drafts/rbogos/default?martech=off
> MWPW-155431 - Don't convert adobe.com urls to stage.adobe.com url

- .github/preview-index/package.json
- .github/preview-index/src/testevent.js
- .github/workflows/run-preview-index-test.yaml
GitHub officially supports the event `resource-published` in GitHub actions. Unofficially it also supports `resource-previewed` but we need to make sure this is true. It is not enabled for forks so this PR has to be merged to do this test.
If this event works we will be able to properly index previewed resources instead of current "index all" process that runs on every 2 hours.
Resolves: [MWPW-155686](https://jira.corp.adobe.com/browse/MWPW-155686)
**Test URLs:**
- After: https://mwpw155686preview--cc--bozojovicic.hlx.live/?martech=off
> MWPW-155686 Catalog Milo: Preview Index Follow Up

- creativecloud/scripts/scripts.js
< @robert-bogos opening this PR from https://github.com/robert-bogos/cc/pull/1 >
This PR adds the stageDomainsMap, enabling the conversion of production URLs to their stage equivalents in the stage environment.
More details about this feature can be found in [this discussion](https://github.com/orgs/adobecom/discussions/2880).
Resolves: [MWPW-158444](https://jira.corp.adobe.com/browse/MWPW-158444)
Test URLs:
After: https://mwpw-158444-domains-map--cc--adobecom.hlx.live/careers?martech=off
> [MWPW-158444] Added stage domains map

- creativecloud/scripts/scripts.js
* Add creative.adobe.com and projectneo.adobe.com/ to stage domain mapping
Resolves: [MWPW-159417](https://jira.corp.adobe.com/browse/MWPW-159417)
**Test URLs:**
- Before: https://stage--cc--adobecom.hlx.live/drafts/ruchika/sstage-domain?martech=off
- After: https://creativecloud--cc--adobecom.hlx.live/drafts/ruchika/sstage-domain?martech=off
> MWPW-159417-Update stage domain mapping

- creativecloud/scripts/utils.js
Removing www.adobe.com from stageDomainsMap to avoid transformation of modals URLs.
Resolves: 
[MWPW-162305](https://jira.corp.adobe.com/browse/MWPW-162305)
[MWPW-162339](https://jira.corp.adobe.com/browse/MWPW-162339)
**Test URLs:**
Before: 
- https://main--cc--adobecom.hlx.page/creativecloud/plan-recommender/quiz-results?quizkey=cc-quiz&martech=off&georouting=off 
- https://main--cc--adobecom.hlx.page/ca/products/aftereffects?instant=2024-11-15T14:00:00.000Z
After: 
- https://mwpw-162305-modal-sticky-banner  --cc--adobecom.hlx.page/creativecloud/plan-recommender/quiz-results?quizkey=cc-quiz&martech=off&georouting=off 
- https://mwpw-162305-modal-sticky-banner  --cc--adobecom.hlx.page/ca/products/aftereffects?milolibs=mwpw-162305-modal-sticky-banner--milo--mirafedas&instant=2024-11-15T14: …
> MWPW-162305: [Black Friday] CTA not visible on CRM due to sticky banner

- creativecloud/scripts/utils.js
This reverts commit 7b3ad286441c925b949982632a9c9b6972f524e0.
https://revert-7b3ad286441c925b949982632a9c9b6972f524e0--cc--adobecom.hlx.live/careers?martech=off
> Revert "removed adobe.com from stageDomainsMap (#450)"

- creativecloud/scripts/utils.js
- test/scripts/scripts.test.js
On preview page, we need to change the domain of all links from adobe.com to the preview domain *--cc--adobecom.hlx.page except for TWP and CRM links. They need to stay on adobe.com since we have them only on that domain.
With `'www.adobe.com': 'origin'` we were replacing adobe.com with the origin in all links.
Now with `'www.adobe.com(?!\\/*\\S*\\/(mini-plans|plans-fragments\\/modals)\\/\\S*)': 'origin'` the domain will not be replaced for TWP and CRM links.
Test page: /drafts/bozo/modal-domain-test
Resolves: [MWPW-162305](https://jira.corp.adobe.com/browse/MWPW-162305)
**Test URLs:**
- After: https://mwpw162305modaldomain--cc--adobecom.hlx.live/?martech=off
> MWPW-162305 Modal domain switch

- creativecloud/features/cc-forms/forms/demandbase.js
* Fix for not showing the Demandbase Popover when the API has no valid response
Resolves: [MWPW-164488](https://jira.corp.adobe.com/browse/MWPW-164488) (partly)
**Test URLs:**
- Before: https://ccqa--cc--adobecom.hlx.live/drafts/mathuria/dalpforms/perpeptual?martech=off
- After: https://demandbase-fix--cc--adobecom.hlx.live/drafts/mathuria/dalpforms/perpeptual?martech=off
> Hide the Demandbase Popover when the API has no valid response -- bug fix

- creativecloud/features/cc-forms/forms/demandbase.js
* [Demandbase] Enables 'Disabled' field for prepopulating the value based on parent field
Resolves: [MWPW-164488](https://jira.corp.adobe.com/browse/MWPW-164488)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/drafts/suhjain/forms/connect?martech=off
- After: https://demandbase-fix-2--cc--adobecom.hlx.live/drafts/suhjain/forms/connect?martech=off
> MWPW-164488 - When the country seen populated with the demand base selection the state field is not seen getting enabled - Fix

- creativecloud/features/interactive-components/start-over/start-over.js
- creativecloud/scripts/utils.js
* The icon's used in accessibility controls were targeted while fetching the start-over icon, This behaviour is fixed in this PR.
Resolves: [MWPW-164085](https://jira.corp.adobe.com/browse/MWPW-164085)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/drafts/sharathkannan/accessiblity/startover?martech=off
- After: https://mwpw-164085--cc--sharath-kannan.hlx.live/drafts/sharathkannan/accessiblity/startover?martech=off
> Fix(Mwpw:164085): The icon beside 'Start over' is missing in interactive marquee.

- creativecloud/features/cc-forms/components/textfield.js
* Fixes the zip/postal code validation pattern to include zipcodes with a space (eg. Canada, UK)
Resolves: [MWPW-166392](https://jira.corp.adobe.com/browse/MWPW-166392)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/drafts/mathuria/dalpforms/perpeptual?martech=off
- After: https://zipcode-fix--cc--adobecom.hlx.live/drafts/mathuria/dalpforms/perpeptual?martech=off
> [MWPW-166392] Zip/postal code validation pattern

- .github/workflows/servicenow.yaml
* Stopping the CMR creation workflow as there is some issue with service now api where Change ID is not returned after CMR creation. Aaron is working with Service Now team to get this resolved.
* Will enable this workflow once we get this resolved
- Before: https://stage--cc--adobecom.aem.live/?martech=off
- After: https://cmr-workflow--cc--adobecom.aem.live/?martech=off
> Stop CMR creation in github workflow for

- tools/sidekick/config.json
Reverts the config file changes of #621
Before: https://main--cc--adobecom.hlx.live/products/photoshop?martech=off
After: https://hlx5-config-revert--cc--sharath-kannan.hlx.live/?martech=off
After-2: https://hlx5-config-revert--cc--sharath-kannan.hlx.live/products/photoshop?martech=off
> reverting the config file to support localization

- creativecloud/features/cc-forms/forms/trials.js
Reverts adobecom/cc#629
Test URLs:
Before: https://main--cc--adobecom.aem.live/?martech=off
After: https://revert-629-errorpagefix--cc--adobecom.aem.live/?martech=off
> Revert "MWPW-168029 | Correct error page for forms error"

- tools/sidekick/config.json
Reverts https://github.com/adobecom/cc/pull/627
Test URLs:
Before: https://main--cc--adobecom.aem.live/?martech=off
After: https://revert-628-hlx5-config-revert--cc--adobecom.aem.live/?martech=off
> Revert "reverting the config file to support localization"

- creativecloud/features/cc-forms/components/checkbox.js
- creativecloud/features/cc-forms/components/dropdown.js
- creativecloud/features/cc-forms/components/textfield.js
Error message and dropdown values rendered is not seen retained in device , shown as flash and disappear
Add your specific features or fixes
Resolves: [MWPW-165929](https://jira.corp.adobe.com/browse/MWPW-NUMBER)
Test URLs:
Before: https://main--cc--adobecom.aem.live/?martech=off
After: https://ccqa--cc--adobecom.aem.live/?martech=off
> MWPW-165929 | Error message and dropdown values rendered is not seen retained in device , shown as flash and disappear

- creativecloud/blocks/unity/unity.js
Migrating CC to unity V2 for performance and flexibility - remove double loads
Resolves: [MWPW-157950](https://jira.corp.adobe.com/browse/MWPW-157950)
**Test URLs:**
- Before: https://main--cc--adobecom.aem.live/products/photoshop/edit-photos?martech=off
- After: https://unityv2migrationfix--cc--adobecom.aem.live/products/photoshop/edit-photos?martech=off
> MWPW-157950 | Migrating CC to unity V2 for performance and flexibility

- creativecloud/scripts/utils.js
* Updated the pdf viewer api's clientid to support hlx.(page|live) aem.(page|live)
Resolves: [MWPW-168400](https://jira.corp.adobe.com/browse/MWPW-168400)
**Test URLs:**
- Before: https://main--cc--adobecom.aem.live/drafts/sharathkannan/12-ways-to-get-the-most-out-of-creative-cloud-for-teams?martech=off
- After: https://hlx5pdf--cc--sharath-kannan.aem.live/drafts/sharathkannan/12-ways-to-get-the-most-out-of-creative-cloud-for-teams?martech=off
PS: The pdfs in the above url can be viewed only after merging it to the main branch.
> MWPW-168400 | Updated pdf api clientId

- creativecloud/scripts/utils.js
Reverts adobecom/cc#610
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/nz/drafts/siva/learn?martech=off
- After: https://revert-610-mwpw-153103--cc--adobecom.hlx.live/nz/drafts/siva/learn?martech=off
> Revert "MWPW-153103: creativecloud.adobe.com URLs not transforming during milo localization"

- creativecloud/blocks/upload/upload.css
- creativecloud/blocks/upload/upload.js
Adding the following style/layout updates to align with Figma for April workflow.
- Update drop-zone area to change dashed line to solid blue line on hover/drag over.
- Update vertical spacing for "file size" text on mobile and tablet.
- Update tablet breakpoint to add rounded corners to image/video.
Resolves: [MWPW-170983](https://jira.corp.adobe.com/browse/MWPW-170983)
**Test URLs:**
- Before: https://main--cc--adobecom.aem.live/drafts/rclayton/upload-poc?martech=off
- After: https://unity-upload-april-updates--cc--adobecom.aem.live/drafts/rclayton/upload-poc?martech=off
> Layout and styling updates

- tools/sidekick/config.json
Before: https://main--cc--adobecom.aem.live
After URL: https://trusted-hosts--cc--adobecom.aem.live?martech=off
> chore: Configure Trusted Hosts for Sidekick

- creativecloud/features/cc-forms/components/dropdown.js
- creativecloud/features/cc-forms/forms/connect.js
* Connect form submission failing if treatment id is set to a invalid format value. Adding a validation check as configured in backend to avoid invalid payload issue.
* Connect purchase intent dropdown needs to populate from en content. Making the odin endpoint explicitly point to us.
Resolves:
[MWPW-170275](https://jira.corp.adobe.com/browse/MWPW-170275)
[MWPW-171455](https://jira.corp.adobe.com/browse/MWPW-171455)
**Test URLs:**
- After: https://MWPW-171455--cc--adobecom.aem.live/?martech=off
Test URL - 
https://dev--cc--adobecom.aem.page/drafts/mathuria/dalpforms/connect
> MWPW-170275 & MWPW-171455 | Connect form treatmentid and purchase intent dropdown fix

- creativecloud/features/interactive-components/selector-tray/selector-tray.js
-  Fixed multiple links have the same programmatic link text but different destinations. 
Resolves: [MWPW-172492](https://jira.corp.adobe.com/browse/MWPW-172492)
**Test URLs:**
- After: https://mwpw-172492-interactive-marquee--cc--adobecom.aem.live/?martech=off
> MWPW-172492: fixed multiple link text for a11y

- creativecloud/blocks/cc-forms/cc-forms.css
Prevent dropdown arrow overlap with content for rtl locale
Resolves: [MWPW-173290](https://jira.corp.adobe.com/browse/MWPW-173290)
**Test URLs:**
- After: https://MWPW-173290--cc--adobecom.aem.live/?martech=off
https://dev--cc--adobecom.aem.page/drafts/mathuria/dalpforms/perpeptual
> MWPW-173290 | Prevent dropdown arrow overlap with content for rtl locale

- creativecloud/features/cc-forms/forms/unsubscribe.js
* [Accessibility]checkbox selection via space bar and enter is not seen functioning in unsubscribe url
*unsubscribe flow for Adobe Promotional Marketing email communications service is seen redirecting to 404
Resolves: [MWPW-173696](https://jira.corp.adobe.com/browse/MWPW-NUMBER)
Test URLs:
Before: https://main--cc--adobecom.aem.page/drafts/suhjain/forms/unsubscribe
After: https://mwpw-173695--cc--adobecom.aem.live/
Testing links:
/drafts/suhjain/forms/unsubscribe?p=QvTylbSZMKjEOgdnTDj%2FcXFRp4rfULx3c6nlD%2FTp7H3ZC4uziIcucjD1%2BnuhMBff0rbACuff37ei5QOKm8in1vfqh1Y%2F4FLjYRD1D0Gl3iZ2R5yQy1VDh35gb9HZunoVZpGDjm3Kk0QN6O%2BqqpmRA6RC4n7Yj%2BSUE%2BetlXJWgWBCQ%2BatWSWMgLmrwnJZnrwMWQ%3D%3D&src=aci&type=macrupdates&n=sV0eIhWBHdVZH5qvsTHAkw%3D%3D&email=d******5%40at.com&legacy=false#
> MWPW-173695 and MWPW-173696 unsubscribe forms

- creativecloud/features/interactive-components/selector-tray/selector-tray.js
- Improved accessibility of ‘Select a variation’ by adding ARIA roles and arrow key navigation for better screen reader support.
Resolves: [MWPW-173532](https://jira.corp.adobe.com/browse/MWPW-173532)
Also Resolves: [MWPW-172065](https://jira.corp.adobe.com/browse/MWPW-172065)
**Test URLs:**
- After: https://mwpw-173532-select-variation-a11y--cc--adobecom.aem.live/?martech=off
> MWPW-173532: Fixed select a variation tray for a11y

- creativecloud/blocks/cc-forms/cc-forms.css
Resolves: [MWPW-173820](https://jira.corp.adobe.com/browse/MWPW-173820)
**Test URLs:**
- After: https://mwpw-173820--cc--adobecom.aem.live/?martech=off
Url:
https://www.stage.adobe.com/mena_ar/creativecloud/animation/testdoc/syt/connect.html#
> [MWPW-173820] Fixed - No spacing between the consent text and check box for arabic locales in forms

- creativecloud/blocks/sidenav/sidenav.js
- test/blocks/sidenav/sidenav.test.html
- test/blocks/sidenav/sidenav.test.html.js
fix taxonomy link to be taken from href, not link text
this was causing Catalog page to request hlx.live url from www.adobe.com
Resolves: [MWPW-175156](https://jira.corp.adobe.com/browse/MWPW-175156)
**Test URLs:**
- After: https://MWPW-175156--cc--adobecom.aem.live/?martech=off
> MWPW-175156: fix sidenav requesting hlx.live

- .github/preview-index/src/sharepoint.js
Updates the preview request path to aem.page since https://main--cc--adobecom.aem.page/cc-shared/assets/query-index-cards-preview.json?sheet=catalog is used for preview in the catalog page.
Resolves: [MWPW-177234](https://jira.corp.adobe.com/browse/MWPW-177234)
**Test URLs:**
- After: https://mwpw-177234--cc--adobecom.aem.live/?martech=off
> MWPW-177234: update hlx.page to aem.page

- .github/preview-index/src/sharepoint.js
this PR has no impact to CC website.
Resolves: [MWPW-177234](https://jira.corp.adobe.com/browse/MWPW-177234)
**Test URLs:**
- After: https://mwpw-177234-2--cc--adobecom.aem.live/?martech=off
> MWPW-177234: revert aem admin url

- creativecloud/blocks/firefly-gallery/firefly-gallery.css
* Corrected z-index for ff-gallery overlay which was conflicting with promobar
Dev validation:
Resolves: https://jira.corp.adobe.com/browse/MWPW-181890
**Test URLs:**
- Before: https://main--cc--adobecom.aem.live/drafts/nthakur/ff-video-gallery-poc?martech=off
- After: https://mwpw-181890-ffgallery-overlay--cc--adobecom.aem.live/drafts/nthakur/ff-video-gallery-poc?martech=off
> MWPW-181890 Fixed FFGallery overlay colliding with promobar
